### ISSUE TITLE
Save state, wrong cpu position get saved (Char specific)

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#114]
### Replicating the issue:

- Savestating with the cpu touching the ground

- After Load State the cpu appear falling from the top of the screen, the result is fine if a save state is done when cpu is airborne

![ezgif-6-020b9b947297](https://user-images.githubusercontent.com/38522864/88287979-64e3ee80-ccf3-11ea-9e64-4bf239a77f68.gif)

### Update!

- This problem seems to be specific with Richter, i have not tested all the chars

**Comment by jugeeya** [comment]
Fixed with a7da2c15bccf8bbae74994f8f305199b004be900 .
