### ISSUE TITLE
Playback Recording

### ISSUE THREAD

**Issue by SaiyanMario** [jugeeya/UltimateTrainingModpack#116]
Many if not all Fighting games have this feature called playback recording and I think the modpack would benefit a lot from it as it'll make it easier to lab against specific scenarios
Example: https://www.youtube.com/watch?v=6_7Tm2HjmyQ

**Comment by jugeeya** [comment]
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/78 .
