### ISSUE TITLE
Missed Tech options with Snake's dthrow

### ISSUE THREAD

**Issue by svanstrijp** [jugeeya/UltimateTrainingModpack#125]
When [Tech Options] -> [Miss Tech] is enabled, It would be valuable if we are also able to choose what action comes next. 
I would like to see another drop-down menu with [Miss Tech Options] : 1. Neutral Getup 2. Roll left 3. Roll right 4. Getup-attack 5. do nothing.
This would make practicing missed tech followups (Including Snakes Dthrow, which basically acts like a missed tech) a lot easier!

**Comment by jugeeya** [comment]
Added in the latest beta.

**Comment by svanstrijp** [comment]
Great! I've tested the latest beta, and it works like it should on missed techs. However it does not register on Snake's d-throw. Is it possible to make it function in that situation as well?
Also, I noticed that regular tech options don't work at all in this beta version.

Thanks for the hard work!

**Comment by jugeeya** [comment]
Lemme reopen and address these.
