### ISSUE TITLE
Double Double Jump Mash and Infinite DJs

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#130]
![image](https://user-images.githubusercontent.com/58751053/89948249-0e007380-dc26-11ea-883d-e24305de97d0.png)

Out of Hitstun the CPU is doing two double jumps. This can potentially make DJ Mashing inaccurate.

E: As as result the Follow-up Mash is always one frame too late, because it's doing the second DJ first

Additionally, the CPU can mash DJ out of hitstun independendly of if they actually used their double jump.

This makes testing longer combos where you intentionally catch their buffered DJ impossible.

**Comment by jugeeya** [comment]
Are you on the *latest beta*? It shouldn't be possible anymore.

**Comment by Yikarur** [comment]
You're a magician! I used the one from yesterday.
