### ISSUE TITLE
Hitbox Scaling and Length

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#131]
Hitbox Scaling is wrong for Yoshi again

![image](https://user-images.githubusercontent.com/58751053/89948890-3472de80-dc27-11ea-9504-a3152e4f3503.png)

The Hitbox Visualization is also one frame longer active than the hitbox

![image](https://user-images.githubusercontent.com/58751053/89948957-58362480-dc27-11ea-9f8e-113304ca7f25.png)

**Comment by jugeeya** [comment]
Fixed in the latest beta.
