### ISSUE TITLE
v2.05: Mash Toggles broken

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#132]
When using certain mash toggle setups the CPU is suddenly starting to mash fsmash and ignores the toggle.

Example:
Mash Toggle (Jump) -> Followup Toggle (Airdodge) 
Mash Toggle (Spotdodge) - instead of spotdodging he will start spamming fsmash (Same for Roll F and Roll B

When I use Mash Toggle (Attack), (Back Air) and jab him, he'll start to spam jab instead

The Mash toggle is basically unusable in that version

Used the latest version from 1 hour ago

**Comment by jugeeya** [comment]
@Yikarur once the new beta releases, can you test again? Sids just put out a fix.

**Comment by Yikarur** [comment]
I tested the beta just released

When I jab on (attack) (bair) he will now do a bair but most situations still don't work properly.

Now Roll F causes Mario to roll (instead of fsmashing) but he starts spamming fsmash AFTER the roll this time.

(Jump) -> (Airdodge) still doesn't occur and he will start fsmashing after landing as well

Mash Toggle (Airdodge) doesn't work at all btw. In tumble he will do nothing and in no tumble he'll start spamming fsmash.

**Comment by jugeeya** [comment]
> Now Roll F causes Mario to roll (instead of fsmashing) but he starts spamming fsmash AFTER the roll this time. 
> (Jump) -> (Airdodge) still doesn't occur and he will start fsmashing after landing as well

Are you sure you don't have FSmash as the follow-up toggle?

 
> Mash Toggle (Airdodge) doesn't work at all btw. In tumble he will do nothing and in no tumble he'll start spamming fsmash.

Just pushed a fix for this.

Can you retry with the latest beta once again, once it releases in a couple minutes? Thanks for being patient and verbose with your bug reports!!

**Comment by Yikarur** [comment]
I tested it and the fsmash spamming bug doesn't occur either!
Seems to be fixed :) 

Thank you and good job!

**Comment by jugeeya** [comment]
Awesome!!
