### ISSUE TITLE
Loading Save States Doesn't Work as/against Pokemon Trainer

### ISSUE THREAD

**Issue by remziz4** [jugeeya/UltimateTrainingModpack#148]
Pressing Up Taunt + Grab to load a save state as Pokemon Trainer doesn't work. The "explosion" triggers, but instead of moving back into position, the next Pokemon simply spawns from the angel platform.

**Comment by KingCalamity** [comment]
Also after respawning then changing to Charizard or Ivysaur, your attacks don't have hit boxes and sometimes Charizard's model freezes.

**Comment by jugeeya** [comment]
Merged issue into https://github.com/jugeeya/UltimateTrainingModpack/issues/154 .
