### ISSUE TITLE
Bayonetta Smash Attack Hitboxes

### ISSUE THREAD

**Issue by KingCalamity** [jugeeya/UltimateTrainingModpack#149]
Bayonetta's up, down, and side smash attacks only have active hitboxes of about 2 to 3 frames according to ultimateframedata.com but the hitbox visualizer hows that they are active the entire time the animation is out.

**Comment by jugeeya** [comment]
Duplicate of https://github.com/jugeeya/UltimateTrainingModpack/issues/131 .
