### ISSUE TITLE
KO Explosion still occurs if you load a save state while being in Tether State

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#151]
The enhanced save state load doesn't have the KO Explosions anymore which is really amazing!

But during Tether state it still has the explosions.

Back to back frames:

https://i.imgur.com/rc6v7SL.png
https://i.imgur.com/A5bLOkw.png

Additional examples I tested were ZSS Zair and SideB, Ivys upB and Jokers upB

Doesn't affect the functionality in any way but I still wanted to report this.

**Comment by jugeeya** [comment]
Merged issue into https://github.com/jugeeya/UltimateTrainingModpack/issues/154 .
