### ISSUE TITLE
Request: SDI Off-Set

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#152]
The current SDI toggle executes frame perfect SDI which is super fun to look at but not really useful to practice with.
There could be a toggle akin to the Reaction Time / OoS Offset Options, which lets you set the number of frames between 2 SDI inputs. 

for example, frame perfect SDI is every 4 frames and with the toggle you could choose if you want them to SDI every 5, 6, 7, 8 .. frames for a more realistic SDI.

**Comment by jugeeya** [comment]
This one should be easy!

**Comment by Yikarur** [comment]
I just realized that it's not super human SDI but actually impossible SDI. 

If there is no option selected in "Mash Toggle" the CPU does SDI every frame even tho it's actually not possible.

When I check any option in Mash Toggle SDI seems to work correctly.

I was really confused when the CPU teleported out of all my combos lmao

**Comment by jugeeya** [comment]
Have you tried the latest beta? I think we fixed that bug.

**Comment by Yikarur** [comment]
I just tried it. It's fixed. Thank you! You're always so fast.
Is there a changelog for betas somewhere so I don't accidently find and post glitches of older betas?

**Comment by jugeeya** [comment]
On the releases page, it'll say "x commits since this release", and you can see that it links to a list of the commits (each one corresponds to a new beta), so that's sort of a changelog. Here's the current one: https://github.com/jugeeya/UltimateTrainingModpack/compare/2.5...master
