### ISSUE TITLE
Save States Don't Work With CPU "Control"

### ISSUE THREAD

**Issue by sidschingis** [jugeeya/UltimateTrainingModpack#153]
Loading a save state while the training dummy is set to "Control" will disable all hitboxes.

**Comment by jugeeya** [comment]
Problem is probably the fact that I'm explicitly checking for `is_operation_cpu`, we may just want to check against FighterId being non-player.

**Comment by jugeeya** [comment]
Merged issue into https://github.com/jugeeya/UltimateTrainingModpack/issues/154 .
