### ISSUE TITLE
Save States issues

### ISSUE THREAD

**Issue by jugeeya** [jugeeya/UltimateTrainingModpack#154]
- ~~As/Against PT (wrong Pokemon, doesn't reset to position)~~
- ~~As/Against IC's (Nana doesn't reset to position)~~
- ~~While one fighter is being star KO'd (they will not respawn)~~
- ~~Loading a save state while hitting someone (they can be passed through)~~
- ~~CPU set to control (super buggy)~~
- Characters in the middle of a tether (KO explosion occur, they don't get moved initially?)

**Comment by Yikarur** [comment]
If you load a save state with someone being on the ledge, they can't get trumped
https://i.imgur.com/r3AQTRD.png

**Comment by remziz4** [comment]
@jugeeya For the Pokemon Trainer issues, I think it may be resolvable by turning off forced swap on death? I hope someone looks into this soon, sucks not being able to use save states with my main :(

**Comment by thepeternguyen** [comment]
Any updates about this for Pokemon Trainer? :/

**Comment by jugeeya** [comment]
As far as I can tell, these are all fixed. A separate issue exists for the last remaining issue with PT in the beta.
