### ISSUE TITLE
Visual Bug: SDI Crest points always upwards

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#157]
The grey half crest is a visual to indicate the SDI direction.

With "Set SDI" no matter what direction the CPU is SDIing the crest is always pointing upward even tho the CPU is SDIng in the correct direction.

Example 1: https://i.imgur.com/2aQigxx.png
The Wolf CPU started on the red line and SDId "out" but the crest is pointing upwards.

Example 2: https://i.imgur.com/sgqsupt.png
This is what Player controlled SDI out looks like. The Mod CPU somehow circumvents the DI Line as well.

This is important, because you use the indicator to adjust your drifting during aerials according to the opponents SDI (well at least I do haha and Luigi players for sure)

**Comment by Yikarur** [comment]
After the DI Indicator got fixed, can this be fixed next?

**Comment by jugeeya** [comment]
Fixed in latest beta.
