### ISSUE TITLE
Tesla Menu with GC Controller

### ISSUE THREAD

**Issue by SmashPyro** [jugeeya/UltimateTrainingModpack#160]
How am I able to open the overlay menu with a gamecube controller? Sorry for noob question :(

EDIT: It worked with using the inner USB Port (Black connector from Original GameCine Adapter). Closed

EDIT2: It only works sometimes. Reopen

**Comment by jugeeya** [comment]
It seems like it may be an issue specific to your setup. Do you have modded triggers? L+X+DPad Left should work otherwise. You can also edit the file `sd:/config/tesla/config.ini` to change the button combo.

**Comment by SmashPyro** [comment]
Thank you for your answer. I tried several original controller and also other configs. All had the same problem. But after some tests and read some threads: It seems that Tesla has a Problem with TV scaleing smaller than 100%. Setting the scale to 100% solved the problem.
