### ISSUE TITLE
An unexpected ban from the Discord server.

### ISSUE THREAD

**Issue by HXAPEWiZZ** [jugeeya/UltimateTrainingModpack#166]
Pre Scriptum: this is not about the Modpack itself, rather about a service indirectly connected to it.

I joined the [Discord server](https://discord.com/invite/qU4TBwV) which this Github repository advertises. If there were any rules there i have read them (I don't remember if there were any), and i did not post anything that would be considered inappropriate by most normal Discord servers, i do remember posting a Captain Falcon clip, but not on which channel, i do think it wasn't out of place on that channel iirc, and it definitely shouldn't be considered offensive. The next day, about 12 hours after i posted my C. Falcon clip, i immediately noticed that the server was not on my list anymore. i immediately dug up the invite again and found out that i was banned. I logged into my alt Discord account, and was banned there as well, even though i never entered that server with that account. perhaps i am IP address banned or MAC address banned or something similar. I did not get a moderator or even a bot mentioning anything about my ban. This is very unprofessional in my opinion, and i hope i am the only one and that it was a error, either way, i would like either an explanation here about my ban, or get me unbanned.

Post Scriptum: This is an awesome Modpack, keep up the good work :D.

Edit: Userame: /g/#0229
ID: 221326153145778177

**Comment by blu-dev** [comment]
While not a moderator, I can tell you why you were banned. You posted this:
![image](https://user-images.githubusercontent.com/42755519/94578601-cb721500-022c-11eb-9aff-6924a7451a8a.png)
I censored out your name and profile picture because I felt I didn't need to target you when I commented on it. You seemed to have conveniently forgotten about this event.

**Comment by HXAPEWiZZ** [comment]
Oh, that explains stuff, i forgot, i am sorry. are there any rules that states that i cannot do that? i will retract it, also it was not meant to insult Mac users or Windows users, i was just kidding about the buzzwords. it was 3 to 5 AM where i live when i posted that after having worked on installing CFW and doing a lot of research on this, so i was not in the best mood and i was also very pissed about some recent political stuff that i couldn't get off my head, ik that is a bad excuse for breaking a rule if i broke any though. if i did not break any rules, i would like to get unbanned, as i have no plans to be offensive there anymore, i need that server for support regarding the mod, and i would use it for that only from now on, even if i did not break any rules.

**Comment by SushiiZ** [comment]
imo, it looks like it was a direct insult to mac and windows users, and well, the terms also affect gay people, just saying "whoops, I didn't mean to" is not a good way to be unbanned, nor a good way to be forgiven, being mad about off topic stuff and saying that stuff in a completely unrelated server will not help your case with the server. they don't need to have stated that that kind of language is unacceptable and you will not be unbanned, you made up excuses, said that language was perfectly acceptable, then threw even more excuses. and you had the privilege to support the modpack within the server, and chose to act like that, so said privilege has been revoked.
