### ISSUE TITLE
Suggestion: Save state also saves character-specific state

### ISSUE THREAD

**Issue by svanstrijp** [jugeeya/UltimateTrainingModpack#172]
It would be a great addition if save state would also save the character-specific states, other than only the position. For example: Wario's waft charge, Joker's Arsene, Steve's weapons/materials. 

Especially saving Wario's waft would greatly improve the training experience with him I feel.

Edit: Saving whether a double jump is used mid-air is also valuable. In the current version CPU's reattain their double jump after loading.

**Comment by jugeeya** [comment]
Mostly done in latest beta. Remaining features are tracked in separate issue.
