### ISSUE TITLE
Tech options?

### ISSUE THREAD

**Issue by lucca65** [jugeeya/UltimateTrainingModpack#18]
Hey @jugeeya finally I got some time to try it out! Awesome tool, already helping my game! I want to know if there are any plans to implement tech options, so we can also add tech chasing to the modpack! Thanks a lot for the hard work and awesome tool!

**Comment by jugeeya** [comment]
Hi @lucca65 . This is, of course, planned! I hope to add it to the "Escape" toggles section. Adding it should actually be quite simple, the flow will probably be to hook some sort of status-related function, check if the status we're changing to is related to teching, then override it with something based on toggles or randomly between the four possible options. Furthermore, it will perform a defensive option *after* the tech option as well (such as flash shield, jab, or spotdodge).

**Comment by lucca65** [comment]
Oh now I saw that we already had a issue opened for that #12, my bad @jugeeya

**Comment by jugeeya** [comment]
No worries, even I had forgotten lol @lucca65 .
