### ISSUE TITLE
Request: DI Cardinal Direction (L, R, U, D)

### ISSUE THREAD

**Issue by b3rt1** [jugeeya/UltimateTrainingModpack#181]
Hi, just an issue I've run into labbing new combos that could be super helpful. As it stands combos that include any attack cancel or RAR have the DI reversed since the direction is tied to which way you're facing. For example, with DI set to out, a downthrow could be DI'd -->, and the attack canceled back air that followed would be DI'd <-- since the attacker is now facing in the opposite direction. It makes learning new combos a little awkward, and having a DI option that isn't tied to attacker direction could be helpful. Thanks for any consideration!

**Comment by jugeeya** [comment]
This is now in the latest beta with Left/Right directions. Don't see too much of a need for up/down for now.
