### ISSUE TITLE
Multiple Save State Slots

### ISSUE THREAD

**Issue by Kemetric** [jugeeya/UltimateTrainingModpack#185]
Save states are awesome! But I think you can go ever further beyond! When going into training mode, there's usually only 1 save state. If I wanted to practice a different combo/setup, I would have to move the characters in the position that I want then save. But what if instead of doing this over and over, we're able to save multiple positions and are able to choose them at will? 

This idea came to me when I decided that I wanted to practice something at the ledge. It was a chore getting the character in the position I wanted, so being able to just go to that after finishing something else would be a blessing.

**Comment by jugeeya** [comment]
Idea for implementation: we have some N (= 5?) slots for save states and the inputs are as follows:

- Grab+Dpad Down: Save State in current slot
- Grab+Dpad Up: Load State in current slot
- Grab+Dpad Left: Switch to previous slot
- Grab+Dpad Right: Switch to next slot

Each of these triggers a notification so it's obvious for the player which slot they're on and so on. And I guess we can save them in a file so it can be remembered between game loads.

**Comment by jugeeya** [comment]
In the latest beta. They are remembered across game loads as well!
