### ISSUE TITLE
Yuzu/Ryujinx emulator compatibility

### ISSUE THREAD

**Issue by Lertsenem** [jugeeya/UltimateTrainingModpack#186]
Is there a way to make this mod work with yuzu? I think it's not possible, but I'm not sure exactly why.

**Comment by Starboomz** [comment]
Not yet, yuzu don't have the framework that the mod needs. If it is going to happen, the mod needs to be remade in the yuzu format.

**Comment by jugeeya** [comment]
Update here: apparently, Ryujinx has Skyline support which unblocks us here. Soon I'll try getting the modpack to work, I suppose with an external application to control the menu as the web interface on Ryujinx does not work currently.

**Comment by jam1garner** [comment]
Yuzu support for skyline plugins can be tracked here: https://github.com/yuzu-emu/yuzu/issues/7392

Yuzu has web browser support, so it might be easier to get working in the case of the training modpack.

**Comment by TheHomerOfSteel** [comment]
Do you continue to get Skyline compatible with yuzu?

**Comment by kir-alt** [comment]
Answer still is no?

**Comment by jugeeya** [comment]
This is in the latest beta for Ryujinx.
