### ISSUE TITLE
Training mod menu doesn't appear while docked

### ISSUE THREAD

**Issue by Themainman1360** [jugeeya/UltimateTrainingModpack#187]
As the title says, the menu fails to appear while docked. It most definitely appears because after inputting the menu buttons, you lose control of the character. By going to the home menu I can see the menu once again even while docked.

**Comment by dgrbrady** [comment]
Hey,I had an issue like this the other day. I realized that in the switch TV Settings, if I had the TV size or zoom or whatever it's called to something other than 100% the menu wouldn't display. Which is a little unfortunate because at 100% it cuts off the edges a little bit for me
