### ISSUE TITLE
Certain hitboxes not popping up

### ISSUE THREAD

**Issue by notjokr** [jugeeya/UltimateTrainingModpack#19]
I started using UltimateTrainingModpack a few days back, and I have to say it has helped me learn a lot about the characters I play as. But I noticed certain attacks either show inaccurate hitboxes, or don't display them at all (or too late)

I didn't see anyone else writing in about this so I figured I should at least report my findings

- Banjo's Side-Special's hitbox starts really late into its attack
- Banjo's Forward-Smash shows an incomplete hitbox
- Banjo's grenade shows no hitbox at all
- Inkling's Splat Bomb shows no hitbox at all

I will post more as I find them, but these are the first few I noticed immediately after setting it up

**Comment by jugeeya** [comment]
I haven't looked into the issues with Banjo, they seem quite interesting and inexplicable.

Many projectiles' hitboxes don't show up, and I mostly chalk it up to the idea that they cannot produce the shield effect graphic. Not proven, but I think that's what it is.

**Comment by notjokr** [comment]
> I haven't looked into the issues with Banjo, they seem quite interesting and inexplicable.
> 
> Many projectiles' hitboxes don't show up, and I mostly chalk it up to the idea that they cannot produce the shield effect graphic. Not proven, but I think that's what it is.

I found another one with Ken's Shoryuken

Hitboxes are shown at the startup of the attack, but disappear as soon as Ken launches off the ground

I haven't tested this with Ryu yet

**Comment by skoolzout1** [comment]
A couple more missing or wonky hitboxes. 
Zss’s Landing Dair hitbox does not seem to show up as she hits the ground. 
Zss’s Jab1 I believe should have 3 hitboxes present, but instead only 1-2 seem to appear.

Sonics spindash SideB hitbox doesn’t seem to appear at the correct time(?) the hitbox does show after a second or so, but during the initial moments of the move, no hitbox is shown. 

I could be incorrect about some of these not working properly. Just something to take a look at when you have a chance. 

I appreciate all of the work you’ve done.

**Comment by jugeeya** [comment]
Most of these are fixed recently. More issues will be opened for different hitbox-related bugs.
