### ISSUE TITLE
Request: Player 2 tilt jump off

### ISSUE THREAD

**Issue by Fangarchomp** [jugeeya/UltimateTrainingModpack#191]
I'm testing survival DI, so I have to use 2 controllers rather than the training mode's DI option (the training mode's DI doesn't last as long as possible to survive.) This is okay, but tilt jump on a controllable player 2 can't be turned off, and seems to be messing with my DI tests. Can you work around this?

**Comment by jugeeya** [comment]
Ideally DI tests shouldn't involve having to use a second controller with this modpack. You should be able to use the existing DI options to test.

**Comment by GradualSyrup** [comment]
This kind of DI test can be done with input recording now, and input recording uses Player 1's controls so you're able to turn off tap jump for it.
