### ISSUE TITLE
Bug: Input Delay option doesn't apply to right trigger

### ISSUE THREAD

**Issue by connorfawcett** [jugeeya/UltimateTrainingModpack#203]
Firstly, thanks for all the amazing work you guys have done on this modpack. Now, for the bug:

I have shield set to both X and right trigger, it seems the input delay setting is not applied correctly to the right trigger, it always has 0 delay no matter what delay is set. From my testing this seems to be the only button affected. I'm using a stock Smash Ultimate edition GC controller. Can provide full configuration if required but I imagine this is recreatable under any conditions.

**Comment by jugeeya** [comment]
Fixed in latest beta.
