### ISSUE TITLE
Could not debug process

### ISSUE THREAD

**Issue by joey-lg** [jugeeya/UltimateTrainingModpack#204]
I am on atmosphere using the supplied files from the homebrew store. After getting tesla, I run smash ultimate with the latest updates. I went to the menu, ran the program and got an error "Could not debug process". Does it have something to do with the new firmware? The hitbox shields work, but the standard smash animations don't show

**Comment by Jumpyuwu** [comment]
I have the same thing. However, I installed it directly from the github and using a sd card

**Comment by joey-lg** [comment]
Well that's just great. Looks like I'm not alone...

**Comment by jugeeya** [comment]
This is solved with the beta release, which will soon become the main release. You can find the beta in the releases/ tab here on Github.

**Comment by joey-lg** [comment]
thanks
