### ISSUE TITLE
Training Mod: Beta Issues

### ISSUE THREAD

**Issue by iOZMinty** [jugeeya/UltimateTrainingModpack#213]
There's a bug where if I pick any options in Mash Toggles, the CPU does nothing. But if I pick options on the Followup Toggles, they work like Mash. What's odd is that when I pick both Followups go first then Mash. And the Mash In Neutral option does not work. I've also noticed that the Shield Options do not work either. Ledge Options just forces the character to let go of the Ledge to regrab it, no matter what option I pick

I'm not sure what is the problem, but I hope it can be solved. Love this project a lot. Hope it grows more. ❤️

**Comment by jugeeya** [comment]
Haven't experienced this on the latest betas which have had many updates, so I will close this. If you still see it, feel free to reopen.
