### ISSUE TITLE
Request: Allow custom stages in training mode

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#237]
For training specific skills, certain custom stages have been created. Custom stages are not accessible in the training mode stage selection menu, so use of these stages requires the user to go into a local versus match instead, and is unable to use the training modpack (except when using the "outside training mode" feature).

Example stage: [https://www.youtube.com/watch?v=qEEgQXvAQK0](https://www.youtube.com/watch?v=qEEgQXvAQK0)

**Comment by GradualSyrup** [comment]
Added with #628
