### ISSUE TITLE
Mash out of grabs/bury/freeze

### ISSUE THREAD

**Issue by jugeeya** [jugeeya/UltimateTrainingModpack#24]

**Comment by Sharnt** [comment]
+Yoshi's Neutral B / Egg lay

I think a good out of these list would be:
Jump
Airdodge
Nair
Waveland in/away

--------

For mashing, some moves don't have to be mashed out ASAP, also some players are worse than others.
So something like:
- Perfect
- Really good (90%)
- Good (70%)
- Average (50%)
- Poor (30%)
- No mash
A random mash option would be only useful for moves like Yoshi's neutral B.

--------

Ideally I'd want also the option to add side / up B for some characters.
