### ISSUE TITLE
Cpu can't be trumped with savestate on ledge

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#242]
If I savestate when the cpu is hanging on the ledge, on consequents loads the cpu cant be trumped (there will be 2 char hanging on the same ledge).

I have ledge delay set to 300

**Comment by jugeeya** [comment]
This is fixed in the latest beta.

**Comment by gnaomo** [comment]
Latest beta

![ezgif-2-2719374b32](https://user-images.githubusercontent.com/38522864/183594520-8f8797c4-c73f-4722-bcf4-2ba2a6979afd.gif)
