### ISSUE TITLE
Can run through opponent after reset

### ISSUE THREAD

**Issue by mmitsui** [jugeeya/UltimateTrainingModpack#255]
Modpack version: 2.6
Player: Young Link
CPU: Any (I tested with BOTW Link)
CPU percentage: 60%
Shield Setting: None
Mash Toggles: Shield
Followup Toggles: None

Step 1) Hit an opponent (used ftilt or grab pummel)
Step 2) Reset (grab+up taunt) immediately on hitstun or during hitstun
Step 3) Run into the opponent. You should be able to run through

This can last for multiple resets. To fix it in-game, just hit the opponent again and reset when the opponent is not in hitstun.

**Comment by jugeeya** [comment]
Likely we can just reenable forcefully with a JostleModule function.

**Comment by jugeeya** [comment]
Fixed in the beta.
