### ISSUE TITLE
Save States - Pokémon Trainer still not working (v3.0)

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#261]
Because I think this is very critical I wanted to emphasize this once more. A whole character community is kept ouf ot the save state feature which is really sad.

Possible solutions:
- Possibly de-activating switch on KO
- if the PT animation is the problem, maybe it's possible to replace the PT respawn, with the default respawn?
- making the Pokémon soloable (this was possible in Brawl, but I have no idea if this is possible in Ultimate modding)

I really hope it's possible to find a solution for this problem.

**Comment by thepeternguyen** [comment]
Have been waiting for a fix for this the past year. Really hope there is some solution, I love playing PT but definitely feel very restricted not being able to use the save state feature...
