### ISSUE TITLE
CPU Training Dummy Recording/Playback Feature

### ISSUE THREAD

**Issue by ShepDogFGC** [jugeeya/UltimateTrainingModpack#263]
This is a mainstay of modern fighting game training modes; recording the training dummy to do some stuff and to playback the inputs. Given my current knowledge of how Smash replays work, this should be possible? Not entirely sure, but this is something that I would LOVE to have in the mod.

Here's an example of what I mean, timestamp included.
https://youtu.be/5vs7O6sZQ9M?t=459

**Comment by jugeeya** [comment]
In the beta in a very WIP form. Will use other more specific issues to track.
