### ISSUE TITLE
Can't open the game (3.0)

### ISSUE THREAD

**Issue by Ezhbasheil** [jugeeya/UltimateTrainingModpack#264]
Hello, 

Ever since I updated the UltimateTrainingModpack to the 3.0 version, I can't open Smash even though it worked perfectly with the beta.

I put screenshots of the message I got and what happens when I select "Details".

![2021091412013400_c 1](https://user-images.githubusercontent.com/63591132/133238249-b931f971-6262-4b3b-b874-692b16899681.jpg)
![2021091412013800_c 1](https://user-images.githubusercontent.com/63591132/133238328-83592908-d5c5-42ec-877a-7bfb305e5873.jpg)

**Comment by jugeeya** [comment]
Can you show what other mods you have? Or files in Smash's atmosphere/contents/ folder?

**Comment by Ezhbasheil** [comment]
I don't have any other mod beside this one and here is how the folders are 

![Capture](https://user-images.githubusercontent.com/63591132/133807397-9ad7df0c-5050-41a0-bd04-65d0da6978b8.png)

**Comment by HXAPEWiZZ** [comment]
> I don't have any other mod beside this one and here is how the folders are
> 
> ![Capture](https://user-images.githubusercontent.com/63591132/133807397-9ad7df0c-5050-41a0-bd04-65d0da6978b8.png)

if you don't figure it out, just back up everything you need, delete everything else, and do a complete reinstallation of atmosphere and hekate and put everything you need back (be sure what you put back don't fuck with this mod), i'd reccommend following this [https://nh-server.github.io/switch-guide/user_guide/emummc/sd_preparation/](https://nh-server.github.io/switch-guide/user_guide/emummc/sd_preparation/) i'm sorry if that's going overkill, but that's what i do when i fuck up, as i value my time, time spent rebooting my switch and booting smash is long if you have to do it more than just once. please feel free to suggest a faster approach, perhaps it's unneeded to reinstall hekate, as it's a bit unrelated lol.

**Comment by jugeeya** [comment]
Please reopen this issue if you still see it on later releases.
