### ISSUE TITLE
Game File Corruption

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#268]
Since 3.0 my game file from the digital version was corrupted twice.

Not sure if it has something to do with the Mod but it's the only game affected so I wanted to bring it up here.

All other games on my MicroSD card work fine.

**Comment by jugeeya** [comment]
Is your SD card formatted as exfat?

**Comment by Semsemboy** [comment]
Had the same problem. Only way I found was to delete the modpack files and with that the modpack. The files are the Trainingmodpack folder in the root of your sd and the exefs and manual_html folders from atmosphere\contents\01006A800016E000. No Idea how to keep the modpack
