### ISSUE TITLE
Grab hitboxes are showing with "Hitbox Visualization" off

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#27]
Tested out with some chars
https://streamable.com/ryh9m

**Comment by jugeeya** [comment]
This is actually quite weird, the code for showing grabboxes and hitboxes each check the same flag whether or not to visualize. Might have to dig deeper. Thanks for pointing this out.

**Comment by jugeeya** [comment]
Fixed in newest beta (releasing shortly).
