### ISSUE TITLE
Request: bring back tesla menu.

### ISSUE THREAD

**Issue by HXAPEWiZZ** [jugeeya/UltimateTrainingModpack#273]
the tesla menu was faster to load, and the frame advantage was a lot easier to see, instead of this barely readable green stuff. I propose to bring back the menu as an option to download, as the tesla menu has some clear advantages over the new web menu and vice versa.

**Comment by jugeeya** [comment]
Maintenance of the Tesla menu is too high for adding new features, as well as it's a huge dependency that might not survive system/Atmosphere updates at times. We are not going to bring it back, we are just going to improve the latency of the menu and use alternate solutions for frame advantage and other displays.
