### ISSUE TITLE
Smashville is not centered, so mirror save states sometimes fail

### ISSUE THREAD

**Issue by Apep-the-snek** [jugeeya/UltimateTrainingModpack#275]
i used Captain Falcon on smashville (no stage hazards), put falcon facing left or right on the very edge of the right top plaform or bottom platform of smashville, and saved the state, when i load this exact position, there is no problem, however when i turn the alternate mirror option on, the mirrored version will make falcon fall as if he's not standing on anything, this happens consistently every time i save state and load it in this way in training mode. is it the smashville stage or the patch itself that is causing this small offset?

**Comment by jugeeya** [comment]
Maybe Smashville is not centered at X-coordinate 0. Not sure... cc @asimon-1  https://rubendal.github.io/ssbu/#/Stage/Smashville

**Comment by asimon-1** [comment]
Correct, the stage is asymmetric. So when we mirror around X=0, you don't end up at exactly the same position relative to the stage. Note that town and city also suffers from this problem.

See the below screenshot from https://tournameta.com/stage-comparison/
![image](https://user-images.githubusercontent.com/40246417/135154971-d55eb5f6-ea4d-4cb4-9c50-2d510adcef82.png)

You can also look at the stage geometry definition here: https://github.com/rubendal/ssbu/blob/master/public/data/patch/12.0.0/stage/Smashville/data.json

**Comment by asimon-1** [comment]
I wasn't able to find the exact platform position with hazards off, but I am confident that it is the same asymmetry issue as the main stage.

**Comment by HXAPEWiZZ** [comment]
> Correct, the stage is asymmetric. So when we mirror around X=0, you don't end up at exactly the same position relative to the stage. Note that town and city also suffers from this problem.
> 
> See the below screenshot from https://tournameta.com/stage-comparison/ ![image](https://user-images.githubusercontent.com/40246417/135154971-d55eb5f6-ea4d-4cb4-9c50-2d510adcef82.png)
> 
> You can also look at the stage geometry definition here: https://github.com/rubendal/ssbu/blob/master/public/data/patch/12.0.0/stage/Smashville/data.json

bruh, that asymmetry, i don't like it lol. i guess this issue is now closed.

**Comment by jugeeya** [comment]
Rather, we might be able to special case Smashville and reflect around a different point for it. It's a common legal stage so it may be worth it.

**Comment by asimon-1** [comment]
Could be. It'd be relatively easy to do I think, for both SV and TnC. Hopefully the platform is centered on the stage...

Not sure we have a way to query the current stage atm, but we could pull some code from smush_info to do that
https://github.com/jam1garner/smush_info/blob/e53bcd1204619d5ee073790d4c37df6c08639fea/src/lib.rs#L30
https://github.com/jam1garner/smush_info/blob/master/src/conversions.rs#L102-L450

**Comment by jugeeya** [comment]
Rather, we can use that same function that smush_info uses, as well as reuse that smush_info library with conversions.
