### ISSUE TITLE
Hero Buff Toggles

### ISSUE THREAD

**Issue by doublesbrian** [jugeeya/UltimateTrainingModpack#28]
Hey, Wasn't sure where to request a feature but thought I'd post it here. Figured you could just delete it if it's not in the right place.

Was wondering if you could add an option in the training pack to always have oomph/psyche up/acceleratle or any combination of them for hero while in training mode. Could be useful for hero's trying to lab combos with buffs, and potentially for other characters playing against hero if you could enable it for CPU too for other chars to test out comboing/kill setups when hero has the buffs too.

Thanks much for your hard work!

**Comment by jugeeya** [comment]
Not a bad idea-- I think I'll open up a different issue with a list of character-specific mods like this one that I can work on. (Like waft, limit, Arsene, monado arts, ...)

**Comment by jugeeya** [comment]
Moved to issue https://github.com/jugeeya/UltimateTrainingModpack/issues/33 .
