### ISSUE TITLE
Suggested feature: Additional Ledge Option (Drop Off Aerial)

### ISSUE THREAD

**Issue by mmitsui** [jugeeya/UltimateTrainingModpack#301]
A ledge option where the CPU does the following:
- Drop off ledge (press back)
- Double jump + press an aerial in the next frame
- (Choice of aerials: neutral, forward, back, down, up)
- Hold forward in the next frame to drift back on stage

Currently to do this, need to set Ledge Option to "wait" and mash options to the aerials.

**Comment by GradualSyrup** [comment]
I think this is definitely best solved with input recording and not as a generic mash option due to how granularly different these options would be for different aerials and characters, so this should be good to be closed. @jugeeya thoughts?

**Comment by jugeeya** [comment]
Agreed.
