### ISSUE TITLE
Buff Menu Problems

### ISSUE THREAD

**Issue by GradualSyrup** [jugeeya/UltimateTrainingModpack#308]
Currently, the buff menu has the following issues:
- Wii Fit heals with deep breathing, meaning repeated save states make her diverge from her initial damage by a large amount
- Little Mac's KO Punch Meter isn't updated properly when the save state is loaded, meaning it won't fill until he hits or is hit by an enemy. He can still use KO punch before this meter is updated.
- Hero's Psyche-Up shakes the screen when you use it, and that transfers over to when he's buffed on save state load, causing the screen to shake on state load whenever this buff is selected.

**Comment by GradualSyrup** [comment]
#321 addresses the Psyche Up issue. Not listed above is another issue to look at, where buff sound effects that are supposed to be cancelled still play if the player is shielding on the first frame of loading the save state (commonly caused by holding grab for a few frames when loading a save state).

**Comment by asimon-1** [comment]
Wii Fit Trainer's deep breath now correctly does not heal when "Save Damage" is enabled, but her damage is set to 0% when "Save Damage" is disabled

**Comment by asimon-1** [comment]
Should also include monado arts in the buffs menu. These are mutually exclusive though so we might need special menu handling for them...

**Comment by GradualSyrup** [comment]
I believe Monado arts are better placed in a character specific menu for Shulk because of how they're mutually exclusive. They behave differently than the other buffs, and it would be nice to have him be able to randomly switch into a different art out of hitstun out of those a player has selected (including not switching as well, as that's a common mix-up).
