### ISSUE TITLE
CPU never rolls right out of missed tech 

### ISSUE THREAD

**Issue by JoeysCodingProjects** [jugeeya/UltimateTrainingModpack#31]
CPU upon being hit and missing tech will only ever normal get up, get up attack, or roll left. They will never use roll right as an option. Setting tech options to random or miss tech has no effect. The option to roll right out of miss tech essentially just doesn’t exist. If you need me to provide anymore info just let me know and I’ll try to find more

**Comment by jugeeya** [comment]
This should be fixed in v1.5... Could you ensure you're on the latest version?

**Comment by jugeeya** [comment]
Ah, wait, out of missed tech... Okay, I'll try and add that.

**Comment by jugeeya** [comment]
Could you try the latest beta release, when you get a chance?

**Comment by JoeysCodingProjects** [comment]
Yeah I’ll download it and get back to you in like 30 minutes

**Comment by gnaomo** [comment]
Tested out and it's not rolling away

**Comment by JoeysCodingProjects** [comment]
> Could you try the latest beta release, when you get a chance?

Ok I downloaded the beta and tested it out. Here's what I've got:

Good news: 
- CPU rolled right out of missed tech

Bad news:
- With **tech options set to random**, and after testing it ~60 times, they only rolled right out of missed tech twice
- With **tech options set to miss tech**, and after testing ~60 times, they never rolled right out of missed tech. Only attack get up, neutral get up, or roll left.

**Comment by jugeeya** [comment]
Okay, I think I've finally found the solution. Now I'm able to test, so I'll post back here once I've solved it.

**Comment by jugeeya** [comment]
@JoeysCodingProjects @gnaomo Please try the latest beta, I believe I've fixed it. Tested it myself as well.

**Comment by JoeysCodingProjects** [comment]
Will test it tomorrow once I find the time and get back to you. Appreciate the hard work and timely fixes!

**Comment by jugeeya** [comment]
I think this is fixed.
