### ISSUE TITLE
Jab Options

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#314]
For characters with both rapid jabs and gentlemen's jabs (such as captain falcon), it would be nice to have a toggle menu option to select which one is performed. 

Special cases to consider:
* If no jab options are selected, only jab 1 would be performed once
* If jab 1 misses, then should the full rapid jab/gentleman's still be performed?
* How long to hold rapid jab before releasing?
* Some characters only have jab 1 (i.e. pichu, pikachu, ganondorf, roy, steve)
* Some characters only have jab 1 + 2 (yoshi, jigglypuff, villager, samus)
* Some characters only have gentleman's (mario, lucas, ike)
* Some characters only have rapid jabs without jab 1 (meta knight, game & watch, zelda)
* Is Mega Man's jab actually a jab or is it an ftilt?
* Do we need to account for Robin's tomes? Idk how that works with jab

**Comment by GradualSyrup** [comment]
This is an incredibly complex implementation that is solved completely and better with our new input recording feature.
