### ISSUE TITLE
OSD doesn't go away

### ISSUE THREAD

**Issue by Jivko1212** [jugeeya/UltimateTrainingModpack#32]
Maybe this is issue with Layoff whose page says it is still not ready to be used.

The problem is that when I change the volume the OSD doesn't go away. Also plugging in shows "charging" which doesn't go away.

Deleting the Training Modpack files from the SD card fixes the issue.

**Comment by jugeeya** [comment]
Yes, this is a Layoff issue unfortunately. But the devs there are actively working on the project, so when they finish their rewrite I bet this issue will go away.
