### ISSUE TITLE
Replay exporting crashing randomly while having the modpack plugins enabled

### ISSUE THREAD

**Issue by antisociable** [jugeeya/UltimateTrainingModpack#326]
Hello so recently I updated to the newest beta version available and anytime I try to export some of my saved replays to videos in game at some random interval the screen will artifact in a way showing odd broken lines and then crash smash brothers. I've tested this rigorously as well as with 2 other people. 1 with the modpack one without. Im about 97% sure something is interfering with something when converting replays to videos and causing the game to crash. If you could investigate this I would appreciate it very much

https://user-images.githubusercontent.com/93240026/160225842-94f6e3bf-e410-41f7-87bf-c16160291054.mov

.

**Comment by asimon-1** [comment]
Can you please try disabling all of your other mods and seeing if the issue persists? The training modpack specifically tries to avoid impacting other game modes, such as Versus mode (including replays). It seems like you have a number of visual mods installed, which seem like more likely culprits than the training mod. It looks like at the time of the crash, you also tried to take a screen capture - does that trigger the crash in a repeatable manner?

If it does persist even after removing all other mods, any additional information you can provide will be helpful:

- Specific characters or scenarios which cause the crash
- System information (HOS version, atmosphere version, arcropolis version, console/ryujinx)
- Time between smash boot and crash
- Any other instances of crashes
- Atmosphere crash report
- Output of skyline logger

**Comment by antisociable** [comment]
I’ve disabled all mods before having online arcropolis and the training mod pack enabled. My mods were all disabled there was no mod folder and it still occurred. I tested it about 20 times doing different steps and repeating. I will attempt to replicate it by trying to screenshot but I don’t believe that’s it. After testing those once more I will send anymore info I have.

**Comment by GradualSyrup** [comment]
Unable to replicate this issue - if it did exist in the past, it's fixed now.
