### ISSUE TITLE
Can’t open the game

### ISSUE THREAD

**Issue by dankey022** [jugeeya/UltimateTrainingModpack#331]
I downloaded the software and it worked for 5 minutes. When I tried to put multiple CPU’s while testing out the features, my game crashed and won’t open.

I tried uninstalling/reinstalling the game and updating the game but nothing changes.
I really need some help, I don’t know what to do.

![image](https://user-images.githubusercontent.com/102884173/161405721-a965dda0-a4fd-4016-8c4f-80c18e9561a9.jpg)

**Comment by Semsemboy** [comment]
Had the same problem. Only way I found was to delete the modpack files and with that the modpack. The files are the Trainingmodpack folder in the root of your sd and the exefs and manual_html folders from atmosphere\contents\01006A800016E000. No Idea how to keep the modpack

**Comment by dankey022** [comment]
Will there be a fix eventually? 

I hacked my switch especially for this

**Comment by Semsemboy** [comment]
Found another way. Delete the files in the TrainingModPack folder and dont set new default settings.
