### ISSUE TITLE
Input Delay bug

### ISSUE THREAD

**Issue by UhyMgi** [jugeeya/UltimateTrainingModpack#338]
v3.2:R button Input Delay does not work.
beta:Actual delay value is greater than Input Delay value.

**Comment by jugeeya** [comment]
Fixed in the beta.

**Comment by UhyMgi** [comment]
beta:Actual delay value is greater than Input Delay value.

**Comment by jugeeya** [comment]
> beta:Actual delay value is greater than Input Delay value.

Can you try with latest? We just put in another fix.

**Comment by UhyMgi** [comment]
Thank you so much.
