### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by Semsemboy** [jugeeya/UltimateTrainingModpack#340]
Hey,

Smash gives an error message when opened. Only way to resolve I found is too uninstall the modpack. Anyone have another solution while keeping the mods?

**Comment by avenetj** [comment]
You probably installed it wrong or have a conflict with other mods (arcr or something)

**Comment by Semsemboy** [comment]
I have no other mods and I'm pretty sure I've installed it correctly

**Comment by Semsemboy** [comment]
After reinstalling the modpack and updating fw to 14.1.1 and atmosphere to 1.3.2 it works now.
