### ISSUE TITLE
Lucas up Air Hit box visualization problem

### ISSUE THREAD

**Issue by Tixo-ssb** [jugeeya/UltimateTrainingModpack#346]
![image](https://user-images.githubusercontent.com/105297581/167648157-c739ac09-a05a-4657-a64d-1a7981be8794.png)

when lucas is turn left and do a up air, the hit box of up air isn't right

**Comment by asimon-1** [comment]
For reference: here is the visualization from ultimate-hitboxes.com
![image](https://user-images.githubusercontent.com/40246417/167649197-9304aa90-fb45-4749-97ba-f07594e8098c.png)

**Comment by jugeeya** [comment]
Hitbox visualization is not being prioritized at this time. At a later date, we will merge in the changes from a more robust visualizer which is also available as a standalone: https://github.com/blu-dev/smash-visualizer
