### ISSUE TITLE
Additional Drop-Down Menus for Mash Toggles: Airdodge, Jump, etc. and Random 

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#35]
If you select different options in "Mash Toggles" you could make it (similar to attack) open a special menu with different variations.

Airdodge 
- Neutral Airdodge
- Left Airdodge
etc.

Jump
- Neutral Jump
- Forward Jump
- Backward Jump

~~Spotdodge~~ -> Dodge
- Spotdodge
- Forward Roll
- Back Roll

For Random, instead of doing random between ALL options (which is too much, because they are mashing useless random specials and aerials as well) you could toggle extra drop down menus when selecting Random and select up to x (whatever number fits) moves that the opponent will be choosing from at random.

Ex. with up to 5 Moves:
Random (new drop down opens up with any option you select)
- Fair
- Backward Jump
- Airdodge
- None
- None

**Comment by remziz4** [comment]
Co-sign, this would be massively useful

**Comment by jugeeya** [comment]
This is kinda fun, really just an interesting design problem. Will work on it ASAP

**Comment by JonasBjordal** [comment]
I was also missing this feature a lot. Hurtbox shifting during retreating jumps out of hitstun matters a ton. Additionally, it'd be very nice to have fastfalled aerials out of hitstun as a toggle. It's very rare that people don't fastfall them to get out of juggles/combos to land as soon as possible.

**Comment by jugeeya** [comment]
This is now implemented.
