### ISSUE TITLE
Compatibility: Smash-Visualizer

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#356]
Blujay's smash visualizer plugin is no longer compatible with the training modpack. When both are enabled, the visualizer plugin fails to display any hitboxes/hurtboxes in training mode, regardless of the training modpack's hitbox visualization setting. The visualizer does not crash, nor does it report any errors in the skyline console logger.

I suspect that the source of the conflict is in `libtraining_modpack_menu.nro`. When both training modpack nro's are disabled or removed, then the visualizer is able to display its hitboxes/hurtboxes.

**Comment by jugeeya** [comment]
Fixed in the beta.
