### ISSUE TITLE
InputDelay bug

### ISSUE THREAD

**Issue by UhyMgi** [jugeeya/UltimateTrainingModpack#360]
After setting the value of InputDelay, when the menu is displayed again, the value of InputDelay changes.

**Comment by jugeeya** [comment]
@UhyMgi Which menu version are you using, the Web Menu or the Quick Menu?

**Comment by UhyMgi** [comment]
Both.
![InputDelay bug](https://user-images.githubusercontent.com/104245709/170623474-ba73f72a-da64-41a5-820f-39c64ea85f59.png)
