### ISSUE TITLE
Feature: Configurable mash triggers

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#366]
It would be nice to be able to select which situations cause the CPU to perform its mash option. I propose a new multiselect submenu with these options:

- When hit
- When airborne
- When an attack is blocked
- When the player is within a certain distance (configurable by another setting)
- After landing
- After a ledge trump
- After a grab/clatter release
- After a ledge option
- After a mistech option
- After a tech option
- After the player taunts or on some specific input
- After a save state is loaded
- Repeatedly whenever possible

This could potentially replace the "Escape Toggles" and "Mash in Neutral" submenus.

**Comment by seanbff** [comment]
I second this. On-hit toggles would be excellent for layered practice, like practicing a neutral interaction into a combo.
