### ISSUE TITLE
Pokémon Trainer Save State Problem Compilation

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#369]
- There occured an infinite switch loop once while I was loading the save state with Player 2. I'm not sure if using Player 2 for loading caused the problem, because I can't reproduce it. 
I had to re-start the game because the error remained even after leaving the training mode.
https://drive.google.com/file/d/1ngQUMxqENv0OY0rGlZ4dmLz-Q1_MEPqq/view?usp=sharing

- If you use a normal training mode reset and then load the save state with the Non-PT Player the Pokémon will not load. It will load, later when the pokémon is hit or when the pokémon is doing any action.
https://drive.google.com/file/d/1nR1HLXdXQOOnD7AaoRD0XoIzls38BCyf/view?usp=sharing
https://drive.google.com/file/d/1ncKga_NvmL_YVhlmS74BsHmnpep8ZKmA/view?usp=sharing
https://drive.google.com/file/d/1nd5DzW5TdFNjdJ5aKYuKBobeiFuNCFb_/view?usp=sharing

- During bug testing for the above I got it to single switch when loading a save state. I was not able to reproduce this yet.
https://drive.google.com/file/d/1nafJ5WCLGHfUxJAd446K_5N2Wy7f6iB8/view?usp=sharing

-  When loading a save state all effects and hitboxes of all other pokémon are turned off and are completely unsuable until the training mode is restarted or the pokémon is saved and loaded.
https://drive.google.com/file/d/1nhyk7maOWZZn4dpBlkWykCJRaUu_nO4R/view?usp=sharing

- Not a bug, but the training mod is completely unusable with or against PT to practice edgeguarding and ledge trapping, because the switches delay the PTs action while the other player can freely move. Additionally the problem with the hitboxes and effects might cripple PTs recovery so edgeguarding after a load is out of question.
https://drive.google.com/file/d/1nWpHIC-pVyMOcHZt_gkQBOxctD9SDFeo/view?usp=sharing

I really hope we can get PT to work like all other characters some day. In Brawl it seems to have been a lot easier to make the Pokémon not force to switch when dying etc. but I will never lose hope!

**Comment by petrikillos** [comment]
From my infinite ignorance, may I ask: 

Why are the characters killed and teleported afterwards on each savestate load, instead of setting previously saved positions and damage values with the "set_pos" and "set_damage" functions?
I'm just curious as to why it's better to kill the characters (which is mainly what causes PT to be such a pain in the ass to fix).

Sorry if this was already asked and answered.

**Comment by Yikarur** [comment]
because just setting the position doesn't reset the stale moves queue.

**Comment by jugeeya** [comment]
Furthermore, characters that aren't dead are harder to teleport (they get stuck on stage geometry, etc.) A quick fix may be to special case PT from this and have staling not reset for the short term. However, a proper fix (PT dying and not switching pokemon) is of course preferred.
