### ISSUE TITLE
DJ Ring is missing with Hitbox Visualization active

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#37]
Same frame: 
https://i.imgur.com/WUdDuc6.jpg Hitbox Visualization: Off
https://i.imgur.com/AS6G1q0.jpg Hitbox Visualization: On

**Comment by jugeeya** [comment]
Fixed with 9841a911272274a6b2a12eb78ea73bc196b24d40 , probably. Will close after testing.

**Comment by jugeeya** [comment]
Confirmed fixed.
