### ISSUE TITLE
Instantly refresh percent numbers on loading saved state, remove slide-up "transition" delay

### ISSUE THREAD

**Issue by AntShrike** [jugeeya/UltimateTrainingModpack#378]
In default Training Mode, a reset using the L + R + A command will instantly set the percent numbers back to whatever they were previously set to. These percents numbers show up IMMEDIATELY on reset.

The modpack's save state + load state feature doesn't work like that though. When you load a state, there's a delay where no percent numbers appear on the screen, and then they slide up from the bottom.

(Pictured in the gif, look at the delay between loading a save state and the percent number appearing)
![ezgif com-gif-maker(9)](https://user-images.githubusercontent.com/96441115/178845705-d270a5bc-6328-4891-9087-c4508ce2e143.gif)
.

It would be amazing if this delay was removed or users given an option to remove it. A lot of people use the modpack to capture footage of very difficult, technical combos, and its a major hassle to reset and wait for the percent numbers to show again before reattempting the combo. Even though the delay is only about a second, that's still time wasted when somebody's attempting a combo 50 or even 100 times to get down perfectly for a clip. 

You'll also see training modpack clips on Twitter or other places where people start the combo before the percent numbers appear, leaving the viewer unsure as to what the starting percent was for the combo. This fix will alleviate that.

**Comment by jugeeya** [comment]
Definitely may need prioritizing, especially considering we may prioritize configurable random percents on save state load. The delay is quite long. It may be ideal to remove death from the save state load, which will also solve the Pokemon Trainer issues. However, we'd need to have a solution for staling.

**Comment by jugeeya** [comment]
Fixed by https://github.com/jugeeya/UltimateTrainingModpack/pull/450 :D
