### ISSUE TITLE
Suggestion: Trigger "defensive options" on normal landing

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#38]
**Settings:**
Mash Toggles: Airdodge
Defensive Options: Flash Shield

If I launch the opponent into the air and try to frame trap him (attack into his airdodge with a low lag move -> punishing his landing) the opponent doesn't toggle the defensive options upon landing.

They only flash shield if the airdodge caused a tech (because they airdodged closed to the ground with transitions into a tech) but if they airdodge and land normally the CPU won't to anything.

but they do use their defensive options if they get hit by a non-tumble move. (Yoshis weak landing nair for example) out of hitstun.

So I guess "defensive option" is triggered by hitstun or get-up options but not by a finishing ending lag / landing lag. 

**My current work around:**
Shield Options: Hold
I let them shield break and attack them while their stunned. They will shield the first available frame after move -> airdodge -> punish but I'd rather have a full shield because I don't know if I really punished them or if it was a really quick shield poke.

kind regards :)

**Comment by jugeeya** [comment]
Yes, "defensive options" currently only function as occurring after a tech getup or a ledge getup. I wasn't sure if forcing them on landing would be annoying or actually useful-- imagine any time that they land, they would perform a defensive option like roll, etc. That's what you want, for it to occur on every landing?

**Comment by Yikarur** [comment]
is there any downside for it to occur on any landing? If you don't want them to do an option upon landing you can simply deactive the defensive option alltogether.

**Comment by JonasBjordal** [comment]
Most people I have spoken too can relate to this request. Shield flicker/spotdodge on normal landing is something I really miss and the workaround is very tedious.
