### ISSUE TITLE
Error: no offset found for function 'load_prc_file'.

### ISSUE THREAD

**Issue by RuiHirano** [jugeeya/UltimateTrainingModpack#382]
Hello.

I would like to create an API for Ryujinx + skyline to retrieve SSBU parameters.

I would like to use the params-hook-plugin, but I get the following error

```
Error: no offset found for function 'load_prc_file'. Refusing to install hook.
```

Here is the system version I am using.

Ryujinx: 1.1.209
NSP: SSBU v13.0.0
libparam_hook.nro: v13.0.1 (pre-release)

How can I solve this problem?
Thank you in advance.

**Comment by jugeeya** [comment]
At first glance, it is likely to be because you are on 13.0.0 smash, but the params-hook-plugin is for 13.0.1. I would suggest upgrading your version of Smash.
