### ISSUE TITLE
Crash Reports Beta October 2022

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#395]
When I opened the menu it stated "Error Code: 2808-1037 - Unable to display page. - Retry" indefinitely until I press B.
The menu was unabled to be opened at all from that point.
Then when I leave the training mode the game black screens when either leaving the character select screen or pressing start.
Afterwards, when I try to re-start the game It usually crashes on start-up but not always. I have the crash report attached:

[01666796894_01006a800016e000.log](https://github.com/jugeeya/UltimateTrainingModpack/files/9870879/01666796894_01006a800016e000.log)

Another error I got was

Error Code: 2--0112
Could not parse the menu response!
Please send a screenshot of the details page to the developers

The details just state:

{}issing field '

**Comment by jugeeya** [comment]
This should be fixed in the latest beta.
