### ISSUE TITLE
Rewrite menu UI using React

### ISSUE THREAD

**Issue by xhudaman** [jugeeya/UltimateTrainingModpack#399]
## Outcomes
- Easier to maintain, and write new menu
- Menu is programmatic, allowing very little front end work to add new features
- Easier to find devs to work on UI
- Ability to build a version of the menu on PC for Ryujinx users

## Requirements

- [ ] Add support for new slider input
- [ ] Fix wonky input
- [ ] React programmatically generates menu UI from Rust generated menu structure JSON
- [ ] Consume the react UI into the plugin
- [x] Add CI/CD pipeline to react for build
- [x] Create reusable MenuButton component
- [x] Add console overrides that commuinicate over websockets
- [x] Improve UX via slight UI changes to button focus states
- [x] Default menu selection is the first one on page
- [x] Move dev tools overrides to a Higher Order Component

**Comment by jugeeya** [comment]
Web menu will be deprecated.
