### ISSUE TITLE
Remapping the button for opening the ModPack menu

### ISSUE THREAD

**Issue by mentalityrl** [jugeeya/UltimateTrainingModpack#40]
I primarily use a gamecube controller. Would it be possible to hold the start button on the Gamecube controller to access the menu?

**Comment by AZ-7** [comment]
Not Jugeeya but he(?) has spoke on this issue before over here. https://twitter.com/jugeeya/status/1190016240003276800

**Comment by jugeeya** [comment]
Fixed in newest beta (releasing shortly).
