### ISSUE TITLE
Stabilize Configurable Button Combos

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#404]
Custom button combinations seem to be unstable at the moment.

Pressing Side Taunt + Up Taunt opens the menu when the config is SPECIAL + UPTAUNT

**Comment by jugeeya** [comment]
Using `_RAW` inputs was the issue. Apparently FGC characters use these.

> Maroof — Today at 4:46 AM
> @CPU_1 Not sure if this helps but regarding the side taunts discussion in dev it's the reason why you can also input Command Specials with Fighting Game characters as well other than using Attack or Special
> Perhaps that tidbit can be handy for FGC inputs used in the modpack
>
> CPU_1 — Today at 4:48 AM
> that's wild, didn't know about that
> you just use side taunt instead of A or B?
>
> Maroof — Today at 4:49 AM
> Yep
> It's pretty handy midair since there's no risk of mis-inputting taunt
> It's why sometimes you might see someone mis-input taunt on the ground when trying to do a motion input on the ground
>
> CPU_1 — Today at 4:51 AM
> very cool, thanks!!
>
> Maroof — Today at 4:51 AM
> You're welcome!
> Oh and also it only registers the "light" version of the input even if you hold down side taunt
> It's similar to how when inputting Grab, the [Attack] portion of the macro dies if you hold buffer it for long enough
> It's good for Mega Man and Steve if you want to buffer full hop pellet/sword jab from the ground

Closed with https://github.com/jugeeya/UltimateTrainingModpack/commit/d0c7a106ca124d091decde0f7c6e5e94affed422
