### ISSUE TITLE
Clatter Mash Trigger Issues

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#406]
1. If I toggle on clatter in the mash trigger menu, it makes mash options persist through savestates in a weird way
2. Also, with double jump set as mash, if I Dthrow the CPU, they will not buffer double jump out of hitstun, but half a second after landing 
3. A Dthrow -> follow-up the CPU will double jump at some point after getting hit by the second move and also jump when landing
4. Mash trigger for clatter + hitstun can cause doubled mash options

**Comment by gnaomo** [comment]
With only clatter mash trigger activated this happens:

after the cpu is grabbed it will wait to perform the clatter mash option based on his percent, the higher the % the longer he waits. (this surely matches the fact that when you grab someone at higher percentages its harder to escape).

![ezgif-4-df6a3f6f6c](https://user-images.githubusercontent.com/38522864/200711245-0c11b195-b1cd-4a9f-bb34-365df33a828b.gif)
