### ISSUE TITLE
Allow us to choose which direction for tech rolls

### ISSUE THREAD

**Issue by AZ-7** [jugeeya/UltimateTrainingModpack#41]
Idk how difficult this is to implement, but something like this I Know would be really beneficial. If its to time consuming feel free to forget this request since I'm not to sure how many people would want this.

**Comment by jugeeya** [comment]
This request comes up a lot, so I'll definitely prioritize this. The only difficult part is determining which direction is "away" vs. "in".

**Comment by jugeeya** [comment]
This is now completed.
