### ISSUE TITLE
Adding SDI Drop-Down Menu

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#42]
Much like DI, selecting the direction which you can sdi, also with the option to choose how much sdi it's applied (Low, Mid, High).

![ezgif-5-2e57b4b26d28](https://user-images.githubusercontent.com/38522864/72810535-13807700-3c5e-11ea-9cae-0a6ce00f3f4e.gif)

**Comment by jugeeya** [comment]
Added in 2.5.
