### ISSUE TITLE
PT CPU breaks when loadstate using Mash Triggers

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#430]
e.g. CPU is set to Mash trigger "Always" and Mash Toggle "Fsmash" (or pretty much every move that changes the fighter kind status), we then load state. CPU will respawn from angel plat.

![ezgif-2-e9f6c1b07c](https://user-images.githubusercontent.com/38522864/201445992-518a8ea7-3698-432a-b493-c3e76cca88b4.gif)

It seems that during the killing process (the very first steps of loading a save state) the code will not get through this statement as usual
https://github.com/jugeeya/UltimateTrainingModpack/blob/db8d9614808f72200351fc4cd063f28838382c0a/src/training/save_states.rs#L251
but instead the mash trigger will override `status` and the code will see that PT CPU is not 'REBIRTH', messing up everything.
_Or at least this my interpretation of what is happening...._

### Normal situation

![image](https://user-images.githubusercontent.com/38522864/201447423-c0cf3acf-0eb5-4c63-a56b-92368bff8ce5.png)

### Bugged out, with Charizard first frame of F-Smash
Next frame will be CPU on angel plat

![image](https://user-images.githubusercontent.com/38522864/201447493-5ff0103e-cb0b-4781-95c8-599f2d27e62c.png)

**Comment by jugeeya** [comment]
Probably we can just check here if save_state.state == NoAction. 

https://github.com/jugeeya/UltimateTrainingModpack/blob/main/src/training/mash.rs#L146
