### ISSUE TITLE
Potential compability issue with ARCropolis (?)

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#434]
I'm using a dark mode training mode skin and with the newest beta it started to bug heavily.

https://i.imgur.com/x6eiOZX.jpeg

The used mod with the folder structure is attached.

[[Training Mode Stage] Dark Mode.zip](https://github.com/jugeeya/UltimateTrainingModpack/files/10033129/Training.Mode.Stage.Dark.Mode.zip)

**Comment by asimon-1** [comment]
@Yikarur I believe this has been resolved. Can you please update Arcropolis to the latest, and the Training Modpack to the latest beta and confirm?

**Comment by Yikarur** [comment]
it works again :) !
