### ISSUE TITLE
Replace native focus ring with a focus class in web menu

### ISSUE THREAD

**Issue by asimon-1** [jugeeya/UltimateTrainingModpack#443]
https://github.com/techyCoder81/hdr-launcher-react/blob/e0d8af6394a227f6bd5f4303bc0d2bc6c19370d6/public/index.html#L7
https://github.com/techyCoder81/hdr-launcher-react/blob/main/src/operations/focus_singleton.ts

This will improve the experience by preventing flickering when dragging slider handles inwards in double-ended-sliders

**Comment by asimon-1** [comment]
If we want it disabled only for certain times, we can disable/enable with
https://github.com/Raytwo/ARCropolis/blob/master/resources/js/arcadia.js#L250
https://github.com/Raytwo/ARCropolis/blob/master/resources/js/arcadia.js#L264

**Comment by jugeeya** [comment]
Web menu will be deprecated.
