### ISSUE TITLE
CPU drops shield before spot dodging/rolling, but not when using other available OOS options. (Beta)

### ISSUE THREAD

**Issue by Akashicgg** [jugeeya/UltimateTrainingModpack#45]
The problem is the same as the title. No matter how I change the settings the AI will always drop shield before performing grab or dodges and rolls OOS. 

I'm on firmware 10.0.1 running on a absolute fresh install of Atmosphere 11 with the beta modpack. Modpack ver 1.5 wouldn't work no matter how I installed it on this version of firmware or firmware 9.1.0, so I used the beta and it seemed to work correctly, but now I'm having this issue.

**Comment by jugeeya** [comment]
This has been fixed for grabs in the latest beta, but not spotdodging yet.

**Comment by jugeeya** [comment]
Fixed in master.
