### ISSUE TITLE
Layoff Menu Doesn't Show Up

### ISSUE THREAD

**Issue by Dadlab** [jugeeya/UltimateTrainingModpack#46]
When I hold the home button on my right joycon, the usual Switch menu shows up instead of the modded toggles. My switch isn't patched, and my microSD is formatted to FAT32. I can still visualize hitboxes and the CPU picks random defensive options/options at the ledge.
It used to work a few weeks ago, but I can't tell what causes this issue.

I have : 
> Reinstalled the latest version of Atmosphère (0.12.0)
> Reinstalled the latest version of the Training Modpack (v1.5)
> Updated my Switch to the latest version (10.0.2)

I have not (yet?) : 
> Reformatted my microSD
> Reinstalled my game

Edit: So all I had to do was installing the beta version of the modpack. If you have a similar problem that should fix it.

**Comment by Luca-GitHubt** [comment]
in TegraRCM, try loadin the payload "fusee-primary.bin" instead of "hekate_ctcaer_5.2.0.bin"
This fixed everything for me!

**Comment by Luca-GitHubt** [comment]
you get the payload "fusee-primary.bin" by downloading the latest version of Atmosphère (0.12.0).
