### ISSUE TITLE
Cannot control the "select fighter with controller" menu while quick menu is up

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#467]
If Player 1 disconnects and the "Select your fighter with the controller you are using"-screen pops up while the quick menu was open, you are not able to select the character. Instead you are blind-navigating the quick menu that is covered by the selection screen.

You can press B until you're out of the quick menu to circumvent that but if this happens on accident you might not know how to act.
So if possible the "select fighter with controller" menu should take priority over the quick menu.

**Comment by jugeeya** [comment]
Great callout. The quickest solution I can think of is to:
- Detect the controller-selection screen
- Turn off the Quick Menu immediately to return control to the user

**Comment by jugeeya** [comment]
Fixed in latest beta.
