### ISSUE TITLE
Crash with 10.0.0 and atmosphere 0.12.0

### ISSUE THREAD

**Issue by danielbao** [jugeeya/UltimateTrainingModpack#47]
Hello! 
Smash Ultimate does not start up with the latest version of atmosphere on 10.0.0. and the modpack installed. Is there an update available for SaltySD or the modpack itself?

Thanks

**Comment by jugeeya** [comment]
Try reinstalling the modpack from the links in release, both 1.5 and the beta have been updated.

**Comment by danielbao** [comment]
Hmmm I'll try it again then. I tried yesterday and got a black screen before even seeing the Nintendo screen pop up. Pressing home would make atmosphere crash. I've checked on the dates in your zip releases that I'm getting the updated version of the files.

**Comment by xiskewer** [comment]
I'm using the latest 1.5 build, and am having the same issue. Opening the homebrew menu also crashes the console.

**Comment by jugeeya** [comment]
Fixed in newest beta (releasing shortly). (please try the new menu and re-raise the issue if the same issue occurs.)
