### ISSUE TITLE
Please add "no DI" in the random DI option

### ISSUE THREAD

**Issue by JonasBjordal** [jugeeya/UltimateTrainingModpack#49]
When practicing reacting to DI there is 3 main DI angles but right now it's only "in" or "away". No DI is also super important as it is extremely common that people try to buffer shield/spotdodge/attack etc before an unreactable move hits them. Covering no DI can often require different execution than the other two as well.

Having all of those 3 DI angles in the "random DI" toggle would make it way more effective for practice. Alternatively, add a toggle menu for DI angles to randomize for more control.

**Comment by jugeeya** [comment]
Good suggestion.

**Comment by jugeeya** [comment]
Fixed in master.
