### ISSUE TITLE
Beta: Menu flips page with ZL/ZR | L /R set to special

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#490]
If you have  ZL/ZR | L /R set to special it will immediately flip a page when opening the menu and will keep flipping pages when the button is held.

**Comment by Yikarur** [comment]
Same problem with Z being set to special.
If I open the menu with Z set to special it will immediately "Reset all".
So X to special will "save defaults"
Y to Special will "reset current" etc.

**Comment by jugeeya** [comment]
We should have the initial button press ignored in general. Not sure how we can do this but maybe via `prev_frame_is_pressed` being set to `true` at init. https://github.com/jugeeya/UltimateTrainingModpack/blob/main/src/common/menu.rs#L123

**Comment by GradualSyrup** [comment]
Closed by #581
