### ISSUE TITLE
Quick Menu; Input Delay Controller Recognition problems when not P1

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#491]
The controls for the quick menu always correspond with the highest player in the switch controller menu. 

This means if my pro controller is Slot2 and I have a GCC connected as Slot1 but I want to use the Pro Controller with the training mod it will use the Slot1 Gamecube Controllers control scheme even though I'm using the Slot2 Pro Controller.

If my Pro Controller is in Slot2 and my Slot1 GCC is not active it will switch to the Pro Controller scheme. If I then activate the Slot1 Gamecube Controller (either because I want to put the CPU to control, or I accidentely touch the GCC) the control scheme will switch to the GCC scheme as well.

Side Note:
If P2 is set to control he can also open the quick menu by pressing Special + Uptaunt but with the corresponding Slot1 control scheme.

**Comment by jugeeya** [comment]
The menu works by grabbing the P1 controller and using that, full stop. This definitely isn't ideal. We have been thinking about using Smash's underlying controls so we can find the controls actually corresponding to the player rather than anything else; that would fix this.

**Comment by jugeeya** [comment]
In the latest beta, the menu uses the controller of Player 1 in Smash, not the controller with the lowest ID. If you can open the menu, that controller is the one which controls the menu. This should be fixed in the latest beta.
