### ISSUE TITLE
Beta: "Hitbox visualization: On" should not be default, because it's still not working correctly

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#493]
There are still the ancient problems of hitboxes like Yoshis for example.

Additionally the hitbox visualization is still visualizing one frame too much for all characters. All hitboxes are active one frame longer than they actually are.

The example in the picture is frame 7 of Yoshis upair (hitbox active 5-6) and frame 16 of Yoshis uptilt (hitbox active 8-15)

![image](https://user-images.githubusercontent.com/58751053/220910733-2a17fb53-eddb-4e95-8ff4-2b123d4ec47c.png)
![image](https://user-images.githubusercontent.com/58751053/220911161-3624c6f8-67f5-4c02-9b02-895cbed084c4.png)

It's probably hard to fix, as this problems have been present for years now but I would make hitbox visualization a non-default for that reason.

**Comment by jugeeya** [comment]
I think we'll leave this for now, as it does help people find out if they have the modpack working for the first time, which is a pretty big deal (we have welcome notifications, but I wouldn't put it past people to ignore them by accident). After that point, users can change their defaults. In the future, we will revamp hitbox visualization so it works and we can track that in the other issue.
