### ISSUE TITLE
CPU doesn't buffer defensive options after footstools or trumps

### ISSUE THREAD

**Issue by JonasBjordal** [jugeeya/UltimateTrainingModpack#50]
This issue applies to both grounded and aerial footstools. Quite a few characters either have a footstool combo or a ledge trump punish, and it would be nice to know whether it's true or not (since the combo counter doesn't apply there). Same goes for more situational combos involving grab release.

As of patch v1.5 the CPU doesn't buffer any defensive/mash options after footstools or trumps. Would be a highly appreciated addition.

**Comment by jugeeya** [comment]
Done with bcd0ca5a286a5f02f10fb2a3096adfd2f8d73fb2 .
