### ISSUE TITLE
CPU doesn't buffer defensive options immediately after tech options

### ISSUE THREAD

**Issue by JonasBjordal** [jugeeya/UltimateTrainingModpack#51]
The CPU seems to only perform the defensive options after a tech animation is finished in its entirety and not accounting for IASA frames. Instead of interrupting the endlag animation, the CPU delays the input by 2 frames for tech rolling backwards and 7 frames for tech in place or tech rolling forwards compared to when I try to buffer those options manually. 

Additionally, when the CPU tech rolls forwards to a ledge/platform edge and ended up getting the "balancing animation", the defensive option input is eaten entirely (roll/spotdodge/jab). The only exception is shield flicker, but it's still delayed by 6-7 frames as mentioned earlier.

This doesn't seem to apply to ledge getups, though.

This issue makes the training mode mod as of v1.5 not reliable for practicing tech chasing and it would be nice to get it patched in the new update.

**Comment by jugeeya** [comment]
Fixed with d2b56ef. Please try out the latest beta and reopen the issue if it isn't fixed.

@JonasBjordal I can't understate the usefulness of the level of detail in the issues you raise. Thank you so much for making these bugs so much easier to diagnose and fix!
