### ISSUE TITLE
Ryujinx Crashes when Loading Into Training Mode

### ISSUE THREAD

**Issue by mpai17** [jugeeya/UltimateTrainingModpack#512]
After installing Skyline and the Training Modpack files, I ran the game and entered training mode. After loading for a while, the game crashes though, and I uploaded the crash logs below. I'm running on update 13.0.0 with all the DLC for Smash, and I'm running the emulator on an AMD CPU and GPU. I'd like to know how to resolve the crash.

[Ryujinx_1.1.681_2023-03-24_22-58-32.log](https://github.com/jugeeya/UltimateTrainingModpack/files/11067941/Ryujinx_1.1.681_2023-03-24_22-58-32.log)
[Ryujinx_1.1.681_2023-03-24_23-00-55.log](https://github.com/jugeeya/UltimateTrainingModpack/files/11067942/Ryujinx_1.1.681_2023-03-24_23-00-55.log)
[Ryujinx_1.1.681_2023-03-24_23-03-40.log](https://github.com/jugeeya/UltimateTrainingModpack/files/11067943/Ryujinx_1.1.681_2023-03-24_23-03-40.log)

**Comment by jugeeya** [comment]
Thanks for the crash logs. It is likely due to newer versions of Ryujinx. You could try downgrading to get unblocked, but I will try to fix this in the beta as well.

**Comment by mpai17** [comment]
Do you know which version of Ryujinx would work atm?

**Comment by jugeeya** [comment]
I am NOT able to reproduce this with a fully restarted setup on Ryujinx 1.1.694 and the latest beta of the Training Modpack. Did you try the beta version by chance? Either way, this may be unrelated to the training mod.

**Comment by mpai17** [comment]
I changed to Smash version 13.0.1 and firmware 16.0.0. I think my Smash version being 13.0.0 was causing the issue, but now it works. Thanks for the help!
