### ISSUE TITLE
Infinite shield still takes damage from some projectiles

### ISSUE THREAD

**Issue by JonasBjordal** [jugeeya/UltimateTrainingModpack#52]
Probably a bug and not a big issue but just wanted to point it out. It seems to only be non-staleable after testing projectiles like Link's Remote Bomb and thrown arrows after picking them up from the ground (neither of them stale). 
However, when arrows are shot normally (in which the get staled) it does no shield damage to infinite shield. Seems to be the recurring theme for other projectiles I tested.

**Comment by jugeeya** [comment]
Fixed.
