### ISSUE TITLE
Blue DI lines are bugged with the random DI option

### ISSUE THREAD

**Issue by JonasBjordal** [jugeeya/UltimateTrainingModpack#53]
As knockback starts, a visual blue line effect indicates the direction you DI (excluding when you don't DI). This can be helpful when trying to react to DI on some moves. A couple of good example are Pikachu/Link Down Throw in which it can let you react ~4 frames earlier on tight follow-ups.

In v1.5, the blue lines are all over the place and doesn't seem to consistently align with the DI direction at all with the random DI option. I couldn't replicate the disconnect of the DI line and the actual DI angle in frame-by-frame with the CPU set to control. As far as I know, the DI (and blue line effect) is decided on the control stick input on the very frame hitlag ends/knockback starts. 

This is not an issue when the CPU is set to DI with a specific angle, only the random DI option, so it's probably a bug.

It would be nice to see it fixed since when practicing now I lose the habit of reacting the blue DI lines since it's not working properly.

**Comment by jugeeya** [comment]
Well this is a bug I wouldn't think would occur, lol. Pretty interesting, thanks for bringing it up. From the way I actually change DI, it makes complete sense. Finding a fix won't be trivial but at least I know some ways I could go about it.

**Comment by jugeeya** [comment]
Notes to self:

Hook `L2CFighterCommon_FighterStatusDamage__correctDamageVectorCommon`, set DI variables at start if it's frame 1, store those globally so we remember and continue to do those. Deprecate old method.

**Comment by jugeeya** [comment]
Fixed in master.
