### ISSUE TITLE
Latest beta and release crashes on atmosphere 0.12.0 and 10.0

### ISSUE THREAD

**Issue by danielbao** [jugeeya/UltimateTrainingModpack#54]
Sorry for re-opening the issue, but I installed the latest beta release and tried the latest release on atmosphere 0.12.0 and I keep on getting the crash. It crashes on 0100000...C and has an error code of 2011-0301. Not sure what's happening, but it seems like you're adding a lot of cool features that I haven't tried yet (save states and shield grab)!

**Comment by jugeeya** [comment]
I just updated the beta. Please try that and get back to me-- you'll also need to delete all of the old training modpack folders.

**Comment by danielbao** [comment]
idk what I did differently b/c I literally clicked download beta the last time and it didn't work. But now it does! I'll just wait for some cool input recording and sdi? It should be pretty similar to the DI right?
