### ISSUE TITLE
Shield disappears when hit 

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#55]
It may be a dumb issue to open lool, is this intentional?
![ezgif-3-483862bb4499](https://user-images.githubusercontent.com/38522864/82047414-12fb6880-96b3-11ea-90f5-126cee62da70.gif)
Also happens to the player
![ezgif-3-1129d196502c](https://user-images.githubusercontent.com/38522864/82047593-5950c780-96b3-11ea-8bad-6dc38d34ed63.gif)

**Comment by jugeeya** [comment]
Fixed in latest commit, will upload new beta later.
