### ISSUE TITLE
Recording Trigger Option

### ISSUE THREAD

**Issue by jugeeya** [jugeeya/UltimateTrainingModpack#578]
None, Save State Load, Save State Save, single-select

Help text should mention that button combination is always possible

**Comment by ShivangRawat30** [comment]
@jugeeya  Hey I am currently learning rust, as it is a good first issue can you please assign this to me

**Comment by jugeeya** [comment]
Hey @ShivangRawat30 , this one is actually pretty in flux in terms of what we want to do, it's not obvious what we are going to end up implementing. Could you find another `good first issue` and let me know and I can help you get started?

**Comment by jugeeya** [comment]
Closed with https://github.com/jugeeya/UltimateTrainingModpack/pull/580
