### ISSUE TITLE
Training Mod overwrites character control {fix is_operation_cpu}

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#58]
If you put the CPU to "control" it still inherits all the training mod options.
I can't manually DI and if I grab the ledge he will auto-choose a ledge option etc.

It's not possible to control the CPU completely manually without deactivating the mod.

**Comment by jugeeya** [comment]
Yeah, I introduced this bug during migration, I'll prioritize fixing it!

**Comment by jugeeya** [comment]
Fixed with 49ffcdc31c583d64ef8db814a851c60a614ce22b .
