### ISSUE TITLE
Shield Bubble disappears when attacking the shield (visual only)

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#59]
I sadly have no idea how to re-create this. A friend practiced the luigi 0-death with "Mash Airdodge" and after a while this happened.

Resetting the training mode with L+R+A didn't fix it. I had to exit the training room.

![shield bug](https://user-images.githubusercontent.com/58751053/82124701-21c04900-97a1-11ea-862e-ee6c712fdcbb.gif)

**Comment by jugeeya** [comment]
Fixed in master, so newer versions of beta + actual release (will) have this fixed.
