### ISSUE TITLE
Stuck during boot

### ISSUE THREAD

**Issue by rookiejet** [jugeeya/UltimateTrainingModpack#6]
Atmosphere 0.8.9 fails to boot with SaltySD spawner. I'm on firmware 8.0.1.

saltysd log:
```
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: got handle 38004 for process
Spawner: SaltySD (pid 7f) asked for handle sdcard
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: got handle 38004 for process
Spawner: SaltySD (pid 7f) asked for handle sdcard
SaltySD Spawner: got SD card
SaltySD Spawner Start
SaltySD Spawner: got handle 38004 for process
Spawner: SaltySD (pid 7f) asked for handle sdcard
```

**Comment by jugeeya** [comment]
Still trying to figure that one out. Apparently using Atmosphere 0.8.8 and booting from fusee-primary.bin (not booting "CFW" from Hekate, if you're using Hekate) works.

**Comment by rookiejet** [comment]
I can confirm it works in 0.8.9 as well booting using fusee-primary.bin. Seems to be a Hekate issue.

**Comment by jugeeya** [comment]
Oh awesome! Thanks so much.
