### ISSUE TITLE
2.0 Hitbox visualization not working properly

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#60]
In the beta, the hitbox visualization was actually working with Yoshi but in 2.0 it doesn't.

https://i.imgur.com/745dnKR.png Beta
https://i.imgur.com/G93lUFO.jpg 2.0

the problem with the beta version was that some hitboxes were partly longer active then they should or a frame too slow but they were at least accurate from the hitbox itself.

**Comment by jugeeya** [comment]
AH I broke it in the last commit, I'll fix it asap. ;_;

**Comment by jugeeya** [comment]
Should work in latest beta.
