### ISSUE TITLE
Include hitstun statuses, current damage in save state

### ISSUE THREAD

**Issue by mk360** [jugeeya/UltimateTrainingModpack#608]
If I hit a CPU with a strong move, and then I immediately save a state then reload it, both characters will respawn in a neutral, non-hitstun status. This issue is more visible with strong aerials (like Byleth's). 
Ideally, I would send a character offstage, then be able to consistently practice their recovery routes and their timing (which includes, among other things, recovering from hitstun at the percent they've been hit at).

**Comment by GradualSyrup** [comment]
Current damage can already be stored in a save state, and this enhancement is not nearly worth the effort investment required. Tumble, DI handling, tumble effects, balloon knockback, hitstun cancel frames etc. would all need to be handled for the hitstun status to be relevant. If you want to practice situations like this, set up how you would want the CPU to be hit offstage, and hit them.
