### ISSUE TITLE
Suggestion: Scrolling through menu points two ways

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#62]
I'm a bit sad about not having the drop-down menu from the old version anymore but this would not be a problem if you could choose the options with "left / right" (or L / R) instead of just pressing A.

Right now you can only scroll through the option by pressing A which means you have to do a full circle if you accidently miss the option you were looking for.

If you could select the option with "left / right" (or at least an extra button that scrolls in the opposite direction) it would be a lot easier to navigate.

**Comment by jugeeya** [comment]
I honestly haven't looked much into what Tesla offers, but at least this one should be easy to do. 

It's just changing this function to respond to left/right inputs:
https://github.com/jugeeya/TrainingModpackOverlay/blob/43583cc2d6f9dab66741f149cb559795e52c8c2a/include/gui_main.hpp#L34-L54

**Comment by jugeeya** [comment]
@Yikarur Added sublists in the latest beta, please try it out!
