### ISSUE TITLE
Save State Load triggers Mash Toggle

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#63]
When you load the save state the CPU will execute the mash option listed.
This is probably because loading a save state puts grounded characters into the jump squad animation and they will land after the save state load is finished which will execute the Mash Toggle.

This does not happen, while a character is when resetting in the air tho (because it uses the ledge grab animation to pull back?)

Here is a frame by frame example, Mario put to "Mash NeutralB"
![frame by frame save state](https://user-images.githubusercontent.com/58751053/82202938-e9388080-9902-11ea-93bc-882e4cf454db.gif)

**Comment by sidschingis** [comment]
Should be fixed by now
