### ISSUE TITLE
Wrong position after load state when under platforms

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#65]
Save state was set on top of center stage
https://gfycat.com/negativeacrobatickissingbug

**Comment by jugeeya** [comment]
Behavior changed with a3ea3e7332642db832a974160560f7ec3b0d64e8 . Now save states are more attached to platforms, still needs fixing, but at least the issue with being under the stage is fixed.

**Comment by jugeeya** [comment]
Fixed with 7e1d8a054fa981d57ce5f77e44886e838baf5121 . (I HAVE NO IDEA WHY IT DECIDED TO WORK NOW BUT I'LL TAKE IT 😍 )
