### ISSUE TITLE
Snake Desync Online

### ISSUE THREAD

**Issue by awesomeme22** [jugeeya/UltimateTrainingModpack#656]
Playing with only Acropolis and Training Mod, no other mods, the game desyncs online at the start of the match if I play snake, only on costumes c01-07.
Newest versions of both plugins.

**Comment by asimon-1** [comment]
@awesomeme22 this doesn't sound like a training modpack issue - can you please remove arcropolis from your SD card (so only the training modpack remains) and see if the issue is still reproducible?
