### ISSUE TITLE
Feedback when using save state

### ISSUE THREAD

**Issue by gnaomo** [jugeeya/UltimateTrainingModpack#66]
I suggest a visual cue or audio cue cause you get no feedback when doing a save state

**Comment by jugeeya** [comment]
Used the Deku flash effect on save state which is generated at the position that the save state will revert to. Try it out in the latest beta.

![image](https://user-images.githubusercontent.com/15069495/82724542-af150900-9c8b-11ea-94ef-d52fa8caaf0a.png)
