### ISSUE TITLE
Panic when replaying CPU actions

### ISSUE THREAD

**Issue by avahe-kellenberger** [jugeeya/UltimateTrainingModpack#660]
![image](https://github.com/jugeeya/UltimateTrainingModpack/assets/34498340/fc6f831c-263d-4b5f-95d1-2a7f50a77413)

Steps:
- Pick Pacman CPU
- Start input recording
- Charge and throw bonus fruit
- Try to replay actions, training mod will panic

This is with the current beta release

---

Testing even further, this is happening with other characters without spawning any items. Happens on multiple stages.

**Comment by avahe-kellenberger** [comment]
UPDATE: The menu option "Playback Button Slots" somehow didn't have any option selected. By selecting an option here, the crash stopped happening.

We should be able to fix this easily by checking if any slot is selected for playback.

**Comment by asimon-1** [comment]
Resolved by #683
