### ISSUE TITLE
Confirmation Pop-up when pressing "Reset All" in the menu

### ISSUE THREAD

**Issue by Antorboy** [jugeeya/UltimateTrainingModpack#664]
It's so easy to randomly missinput and accidentally press Y and lose all your bot settings and it's a bit annoying when you have to redo everything.

Just add a pop-up that says "Are you sure you want to reset all the settings back to default?"

**Comment by asimon-1** [comment]
@Antorboy This should be resolved in the latest beta version. Can you install that and see if it meets your use case?

**Comment by Antorboy** [comment]
It works perfectly, thanks a lot!
