### ISSUE TITLE
Training Modpack Panicking on Startup with Yuzu

### ISSUE THREAD

**Issue by PatrickMiller728** [jugeeya/UltimateTrainingModpack#668]
Installed the latest Modpack update on Yuzu 1722 with Smash Ultimate 13.0.1. On launch I get this message:

![Panic](https://github.com/jugeeya/UltimateTrainingModpack/assets/55297098/b3d38f14-0ad2-47cb-bf76-3715632f0b61)

**Comment by TR4NQU1L1TY** [comment]
I am also experiencing the exact same issue with Yuzu 1732 and Ultimate 13.0.1. Would appreciate any feedback!

**Comment by jugeeya** [comment]
The newest version only supports Smash Ultimate 13.0.2. Please upgrade your Smash version if you want to use this version of the modpack. Otherwise you can use an older version of the modpack.
