### ISSUE TITLE
Reactionary OOS options

### ISSUE THREAD

**Issue by thegimz** [jugeeya/UltimateTrainingModpack#67]
Just think it would be cool to have characters act frame 17 or 18 after you hit their shield to make it more human for oos options. Would mostly effect really quick moves like Luigi's dtilt

**Comment by jugeeya** [comment]
Added with https://github.com/jugeeya/UltimateTrainingModpack/commit/e66550904203b36bccb2ad6e35d68ab1d2aef61f .
