### ISSUE TITLE
2.0 Crash Reports

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#68]
I'll collect all my crash reports here.

If you also want report a crash look into  /atmosphere/crash_reports on your SD card and zip the corresponding files and post them here

Collecting Crash reports will make finding the issue easier so we might get the most stable mod possible!

This crash happened right after waking up from sleep mode. I changed the CPU character on the CSS in training mode to Lucina and started the match.

[crash_reports_18052020_1800_Yikarur.zip](https://github.com/jugeeya/UltimateTrainingModpack/files/4645500/crash_reports_18052020_1800_Yikarur.zip)

**Comment by jugeeya** [comment]
Definitely due to Skyline (backend code mod framework) attempting to send logs, and either the queue gets too backed up or some other reason causes a crash after a while. I'll need to make a PR in [that repo](https://github.com/shadowninja108/Skyline) to remove logging on release builds.

**Comment by jugeeya** [comment]
@Yikarur Thank you so much for providing the crash logs! Was really easy to pinpoint the issue because of them.

**Comment by nharvey27** [comment]
I am getting an error on game startup. I am using atmosphere 0.12.0. 
[01589844043_01006a800016e000.log](https://github.com/jugeeya/UltimateTrainingModpack/files/4647395/01589844043_01006a800016e000.log)

**Comment by jugeeya** [comment]
@Yikarur Could you try using this file? Unzip it and paste it in `atmosphere/contents/atmosphere/contents/01006A800016E000/romfs/skyline/plugins/`.


[libnro_hook.nro.zip](https://github.com/jugeeya/UltimateTrainingModpack/files/4651305/libnro_hook.nro.zip)

**Comment by Yikarur** [comment]
Game crashed when I was trying to create a new tag. The screen went black and the switch froze. I had to hard reset the console.

[crash_reports_18062020_0152_Yikarur.zip](https://github.com/jugeeya/UltimateTrainingModpack/files/4795584/crash_reports_18062020_0152_Yikarur.zip)

**Comment by jugeeya** [comment]
Fixed as of v3.0
