### ISSUE TITLE
SSBU Training Modpack has panicked at 'Failed to find offset for STALE_MENU', src/common/offsets.rs:180:1

### ISSUE THREAD

**Issue by Tixo-ssb** [jugeeya/UltimateTrainingModpack#680]
When I launch the game, a pop up come and said : "SSBU Training Modpack has panicked! Please open the details and send a screenshot to the dev, then close the game. file ="
and when I check the details it said : 
Error Code: 2--0069
SSBU Training Modpack has panicked at 'Failed to find offset for STALE_MENU', src/common/offsets.rs:180:1

help ? ^^'

**Comment by Evergm90** [comment]
got the same error as you. hope we find help soon. need to get some quality training. i tried installing latest version of training modpack and the beta and same error pops up. got the latest version of skyline.
![ult modpack error](https://github.com/jugeeya/UltimateTrainingModpack/assets/105826132/ab7f1341-7df6-4e3a-a705-80e87b58843e)
![ult file location 1](https://github.com/jugeeya/UltimateTrainingModpack/assets/105826132/46ceea98-02fd-4fed-b223-505a76d6d774)
![Uploading ult file location 2.png…]()

**Comment by Evergm90** [comment]
i got the mod to work. the version of my ssbu is 13.0.1 so i think that was the problem with the current version of the modpack. i downloaded a later version the 6.0.1 training modpack . did the same installation . and now it worked

**Comment by BroAkroze** [comment]
> i got the mod to work. the version of my ssbu is 13.0.1 so i think that was the problem with the current version of the modpack. i downloaded a later version the 6.0.1 training modpack . did the same installation . and now it worked

This solution worked for me as well. I suppose I need to update Smash to 13.0.2 to get the new additions.

**Comment by asimon-1** [comment]
Updating both smash and the training modpack will resolve this issue 👍

**Comment by dd145-star** [comment]
![Image](https://github.com/user-attachments/assets/fc74f90a-0d6e-41fc-b6f4-3f095b065f2b) where do I get the latest training mod pack? I redownloaded, replace the atmosphere folder and got this error.
