### ISSUE TITLE
Switch crashes when opening the training mode.

### ISSUE THREAD

**Issue by VitoItalianGamer** [jugeeya/UltimateTrainingModpack#682]
When opening up the training mode the switch crashes with a buzzing sound.

**Comment by asimon-1** [comment]
@VitoItalianGamer this doesn't sound related to the training modpack, we haven't observed any behavior like this before. Can you confirm that you're running:
* The latest version of smash (13.0.2)?
* The latest version of the training modpack?
* No other mods/plugins installed?

**Comment by VitoItalianGamer** [comment]
I happened one time and it doesn't happen anymore thank you.

**Comment by VitoItalianGamer** [comment]
I meant "it".
