### ISSUE TITLE
Failed to find offset for STALE_MENU

### ISSUE THREAD

**Issue by Asancu** [jugeeya/UltimateTrainingModpack#686]
Hello,

I just downloaded the latest version for Ultimate Training Modpack, but it crashed when I tried to open the game. I simply put the three needed .nro files in the skylines/plugins folder ("`libnro_hook.nro`", "`libparam_hook.nro`" and "`libtraining_modpack.nro`").

This is the error I am presented with:

`SSBU Training Modpack has panicked at 'Failed to find offset for STALE_MENU', src/common/offsets.rs:180:1`

Error Code: 2--0069

¿Any ideas about what could be the cause? 

Thank you so much for your help in advance.

**Comment by asimon-1** [comment]
This is caused by a mismatched version of smash+modpack. Please update smash to the latest (13.0.2) and reinstall the modpack from scratch to resolve it

**Comment by Asancu** [comment]
> This is caused by a mismatched version of smash+modpack. Please update smash to the latest (13.0.2) and reinstall the modpack from scratch to resolve it

Oh jeez. Thank you so much for letting me know. This is what you get for being lazy and not wanting to update Switch and Atmosphere. Thanks! I'll try and let you know if this fixes this issue.

**Comment by Asancu** [comment]
Now I've got another error, which says:

"The Ultimate Training Modpack was unable to locate the global hazard address in your version of the game.

Please report this along with your game version.

Hazard control will be disabled for this launch."

Thing is that this game has been updated to the latest version, 13.0.2...

**Comment by Asancu** [comment]
Alright, I managed to make it work! Not sure if it is actually related, but I had some .nro plugins as back up for the older Ultimate Training Modpack version which extension was ".nro.old". I deleted those and then I moved the newer .nro files to the plugins folder. 

Closing issue.
