### ISSUE TITLE
SSBU Training Modpack has panicked at 'Failed to find offset for STALE_MENU', src/common/offsets.rs:180:1

### ISSUE THREAD

**Issue by Drygva** [jugeeya/UltimateTrainingModpack#687]
Error pops in Ryujinx. Followed the installation instructions multiple times. Tried on both 6.10 and the beta.

See attached screenshot for the line of code being referenced. Looks like a name change that wasn't refactored properly as STALE_MENU isn't referenced anywhere else in that file.
![image](https://github.com/jugeeya/UltimateTrainingModpack/assets/19308761/4ad00792-030a-4476-a50e-fa39f3265c2e)

**Comment by asimon-1** [comment]
@Drygva this indicates a compatibility issue with the version of smash that you're running. Please update smash to the latest version and try again

**Comment by Drygva** [comment]
> @Drygva this indicates a compatibility issue with the version of smash that you're running. Please update smash to the latest version and try again

I was able to get it working by using training modpack version 6.0.
