### ISSUE TITLE
SSBU Training Modpack has panicked at 'Failed to find offset for STALE_MENU', src/common/offsets.rs

### ISSUE THREAD

**Issue by Chritiaan** [jugeeya/UltimateTrainingModpack#692]
I am using the mod on ryujinx and it continues to give me this error on the start up of ssbu and wont allow me to load into the game.
![Capture](https://github.com/jugeeya/UltimateTrainingModpack/assets/173527507/84c927a7-8573-4bbb-b89b-24d9e576d33b)

**Comment by GreatCharLi** [comment]
Also getting this issue
![image](https://github.com/jugeeya/UltimateTrainingModpack/assets/172536627/b9dfb1cc-b9d7-4cb0-8351-2a82a999e400)

**Comment by Umbralls** [comment]
Its also saying that for me and i have no idea why 
![Error Number_ 69 (Details) 7_5_2024 10_51_03 PM](https://github.com/jugeeya/UltimateTrainingModpack/assets/133191456/7f2c06ab-2b92-4569-9b99-3d1fc6b17cf4)

**Comment by GreatCharLi** [comment]
I managed to fix this, turns out I was on 13.0.1 but this only works for 13.0.2 :)

**Comment by Umbralls** [comment]
> I managed to fix this, turns out I was on 13.0.1 but this only works for 13.0.2 :)

is this the version for ryujinx i need to be on?

**Comment by GreatCharLi** [comment]
The version of Smash Bros you need to have

**Comment by GreatCharLi** [comment]
> > I managed to fix this, turns out I was on 13.0.1 but this only works for 13.0.2 :)
> 
> is this the version for ryujinx i need to be on?

No, it's the version of Smash Bros you need to have

**Comment by Umbralls** [comment]
> > > I managed to fix this, turns out I was on 13.0.1 but this only works for 13.0.2 :)
> > 
> > 
> > is this the version for ryujinx i need to be on?
> 
> No, it's the version of Smash Bros you need to have

oh ok tysm :D

**Comment by Umbralls** [comment]
ok update from me: i downloaded the right version of smash bros but now instead of giving me an error ryujinx just crashes
