### ISSUE TITLE
Where can I find a more extensive documentation?

### ISSUE THREAD

**Issue by lucca65** [jugeeya/UltimateTrainingModpack#7]
Hey, Also a dev that loves Smash Bros here! I'm VERY GLAD I've found all of this on GitHub.

I'm not familiar with devkits on the switch (only worked with linux development and some web development). Is there somewhere I can find docs on how to get it started on my setup?

Thanks a lot!

**Comment by jugeeya** [comment]
https://vps.werwolv.net/guide/homebrew_dev/introduction.html 

Personally I just found this amazing site. However, note that this repository is a plugin to a [hombrew app]( https://github.com/shinyquagsire23/SaltyNX ), so a lot of the code here is really self-contained. @jam1garner and I are trying to document how to make these sorts of mods over at the [code-mod-framework]( https://github.com/ultimate-research/code-mod-framework ). I hope to write a Wiki soon on how to write mods with that. But you can think of this project as an extension to that framework.

**Comment by lucca65** [comment]
I see, I'll try to make it run on a spare switch so I can continue my online play 😁

If I find success on it I can help on it, if there is a issue to do this, feel free to @ me!

thanks a lot for now @jugeeya
