### ISSUE TITLE
SSBU Training Modpack has panicked at 'Failed to find offset for STALE_MENU', src/common/offsets.rs 

### ISSUE THREAD

**Issue by Mantoine180** [jugeeya/UltimateTrainingModpack#704]
Imo because of the update of SSBU version 13.0.3 the training modpack isn't valid anymore I also had to Update Acropolis.

**Comment by Mantoine180** [comment]
![20241009_202011](https://github.com/user-attachments/assets/9aef59a8-61f7-4c97-b322-631d09ddc826)

**Comment by BlueZabu** [comment]
Definitely because of the update. I'm getting the same issue.

**Comment by monkeymorin** [comment]
Same, also got this same error with the beta branch

**Comment by asimon-1** [comment]
Fixed by #705
