### ISSUE TITLE
Add frame advantage display for moves on-hit and moves on-shield

### ISSUE THREAD

**Issue by 6oh5** [jugeeya/UltimateTrainingModpack#72]
example: https://twitter.com/UnclePunch_/status/1034694297503916033?s=20

Adding a frame advantage display would help labbers easily determine what followups they could get after landing a move in a combo or how they can safely pressure shield. Sites like ultimateframedata.com only display frame advantage for moves that hit shield that are fresh, with fullhop multiplier, and are executed such that the hitbox connects the frame before landing (all of which are not always going to happen in real matches).

**Comment by jugeeya** [comment]
I suppose the ask here is pretty simple, just find the difference between when the player is actionable vs. the CPU is actionable after a hit. The only difficult part is getting a global frame counter, but that is also possible.

**Comment by jugeeya** [comment]
Added in with https://github.com/jugeeya/UltimateTrainingModpack/pull/85 , but will continue to track bugs as they arise.
