### ISSUE TITLE
Hitboxes Visualization is one frame late

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#73]
The visualization for the first active frame is displayed for 2 frames and THEN the other hitboxes come after it which desyncs all moves

First 3 active frames of Yoshis Fair for example:
1: https://i.imgur.com/I6eNPdk.png
2: https://i.imgur.com/UPiFakR.png
3: https://i.imgur.com/pefnbIw.png

Tested this with a lot of moves from different characters and this behavior is on all hitboxes

**Comment by jugeeya** [comment]
Reverted to hitbox scaling issue, so at least it's no longer a frame late. Lol.
