### ISSUE TITLE
More attack toggles

### ISSUE THREAD

**Issue by jew-two** [jugeeya/UltimateTrainingModpack#87]
Would be nice to have all moves available to use for oos and you could practice countering every move with mash in neutral. Also a move option would be cool to use with mash in neutral especially for aerials so maybe walk,run,and dash in between the mashes

**Comment by jugeeya** [comment]
Added in 186c6ddc2dc022b5f8d98c5691751f912db497b0 and a12ae53140d2807e841508684e53c5f2e0c6b8cd.
