### ISSUE TITLE
Infinite shields crashes game 

### ISSUE THREAD

**Issue by jew-two** [jugeeya/UltimateTrainingModpack#90]
The times I try to use infinite shields it will crash my game after a couple minutes sometimes it will crash the first time I hit the shield if I also have an oos option on I've not had it crash with just hold shields yet

**Comment by jugeeya** [comment]
Are you running other Smash mods, by chance?

**Comment by jew-two** [comment]
Yeah I just tested it with saltynx turned off that was the problem
