### ISSUE TITLE
Doesn't do OoS Option on first attack

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#92]
Everytime I reset with L+R+Start the CPU won't do anything on the first hit against the shield.

I guess thats a consequence of the new shield hold function? but on infinite shield the opponent should really do an OoS on first attempt.

**Comment by Yikarur** [comment]
ok I just found "OoS Offeset"
Does that mean I have to hit that many moves to make him do an OoS option? Thats neat but I haven't heard of it yet. 

Delete this

**Comment by jugeeya** [comment]
Yes, we can add more info in the release but the Help text should give some info.
