### ISSUE TITLE
Frame Advantage Counter Issues

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#93]
The following options will change the disadvantage number:

A -10 moves (Yoshis jab) becomes

-11 if I press shield
-16 if I buffer a jump 
-47 on a back roll 
-43 on forward roll
-38 on spotdodge
and other funny things for example buffering egg roll out of jab will extend the frame advantage to up to -262 lmao

even If I add the durations of those options the numbers don't match so thats not the issue.

The frame advantage will update on wrong frames as well. 
For example the Frame Disadvantage will display the -16 on the second airborne frame after jab

**Comment by jugeeya** [comment]
This is now fixed.
