### ISSUE TITLE
Suggestion: Save Stats shouldn't save %

### ISSUE THREAD

**Issue by Yikarur** [jugeeya/UltimateTrainingModpack#96]
Right now you have to L+R+Start anyway to reset stale moves.

So you're permanently conflicing with the Save State Load and the Training Mode % when you change something.

I just don't see any use in saving the % right now. You can adjust the % thanks to the native options anyway

**Comment by jugeeya** [comment]
Save states are meant to be a replacement for L+R+Start, so imagine a world without L+R+Start when considering save states. If staling is fixed for save states, then immediately things like percentages resetting become necessary.

**Comment by jugeeya** [comment]
Since staling is fixed, this can be closed.
